# Generated by Django 4.2.30 on 2026-06-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_groups_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelTable(
            name="empresa",
            table="empresa",
        ),
        migrations.AlterModelTable(
            name="user",
            table="usuario",
        ),
        migrations.AlterModelTable(
            name="usuarioempresa",
            table="usuario_empresa",
        ),
    ]
