# Generated by Django 4.2.30 on 2026-06-18 20:04

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_options_alter_empresa_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="cd_usuario_atualizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas_atualizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="cd_usuario_criacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas_criadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="dh_atualizacao",
            field=models.DateTimeField(auto_now=True, verbose_name="data de alteração"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="dh_criacao",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="data de criação",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="nr_cnes",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[apps.core.validators.validate_cnes],
                verbose_name="CNES",
            ),
        ),
    ]
