# Generated by Django 4.2.30 on 2026-06-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0021_screendefinition_access_key"),
        ("accounts", "0007_user_clinical_security_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Papel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ds_descricao",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="descrição"
                    ),
                ),
                ("sn_ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "grupo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papel",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "db_table": "papel",
                "ordering": ("grupo__name",),
            },
        ),
        migrations.CreateModel(
            name="PapelTela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telas",
                        to="accounts.papel",
                    ),
                ),
                (
                    "tela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papeis",
                        to="core.screendefinition",
                    ),
                ),
            ],
            options={
                "db_table": "papel_tela",
                "unique_together": {("papel", "tela")},
            },
        ),
        migrations.CreateModel(
            name="PapelModulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papeis",
                        to="core.module",
                    ),
                ),
                (
                    "papel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos",
                        to="accounts.papel",
                    ),
                ),
            ],
            options={
                "db_table": "papel_modulo",
                "unique_together": {("papel", "modulo")},
            },
        ),
    ]
