# Generated by Django 5.0.14 on 2026-07-03 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_sync_recent_role_screens"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cd_usuario_atualizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_atualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cd_usuario_criacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dh_atualizacao",
            field=models.DateTimeField(auto_now=True, verbose_name="data de alteração"),
        ),
        migrations.AddField(
            model_name="user",
            name="tp_usuario",
            field=models.CharField(
                choices=[
                    ("USUARIO", "Usuário"),
                    ("ADMINISTRADOR", "Administrador do sistema"),
                    ("AUDITOR", "Auditor"),
                ],
                default="USUARIO",
                max_length=20,
                verbose_name="tipo de usuário",
            ),
        ),
    ]
