"""Operações históricas de dados da migration 0007."""

# Generated by Django 5.0.14 on 2026-07-21 18:46

import django.db.models.deletion
from django.db import migrations, models


def copiar_motivos_conclusao(apps, schema_editor):
    MotivoServico = apps.get_model("tickets", "MotivoServicoSuporte")
    MotivoConclusao = apps.get_model("tickets", "MotivoConclusaoSuporte")
    Empresa = apps.get_model("accounts", "Empresa")
    for motivo in MotivoServico.objects.all():
        MotivoConclusao.objects.update_or_create(
            cd_motivo_conclusao_suporte=motivo.pk,
            defaults={
                "cd_empresa_id": motivo.cd_empresa_id,
                "cd_oficina_id": motivo.cd_oficina_id,
                "nm_motivo": motivo.nm_motivo,
                "sn_ativo": motivo.sn_ativo,
            },
        )
    for empresa in Empresa.objects.all():
        MotivoConclusao.objects.get_or_create(
            cd_empresa_id=empresa.pk,
            cd_oficina_id=None,
            nm_motivo="Realizado",
            defaults={"sn_ativo": True},
        )


def reverter_motivos_conclusao(apps, schema_editor):
    MotivoConclusao = apps.get_model("tickets", "MotivoConclusaoSuporte")
    MotivoConclusao.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0014_user_cd_usuario_atualizacao_user_cd_usuario_criacao_and_more",
        ),
        ("tickets", "0006_alter_ticket_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotivoConclusaoSuporte",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_motivo_conclusao_suporte",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nm_motivo", models.CharField(max_length=120, verbose_name="motivo")),
                ("sn_ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_oficina",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_oficina_suporte",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.oficinasuporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo de conclusão",
                "verbose_name_plural": "Motivos de conclusão",
                "db_table": "suporte_motivo_conclusao",
                "ordering": ("cd_oficina__nm_oficina", "nm_motivo"),
                "unique_together": {("cd_empresa", "cd_oficina", "nm_motivo")},
            },
        ),
        migrations.RunPython(copiar_motivos_conclusao, reverter_motivos_conclusao),
        migrations.AlterField(
            model_name="ticket",
            name="cd_motivo_conclusao",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_motivo_conclusao_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets_concluidos",
                to="tickets.motivoconclusaosuporte",
                verbose_name="motivo da conclusão",
            ),
        ),
    ]
