# Generated by Django 5.0.14 on 2026-08-02 22:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0016_garantir_empresa_celeris_e_acesso_administrativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaPesquisa',
            fields=[
                ('cd_pergunta_pesquisa', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_pergunta', models.CharField(max_length=500)),
                ('tp_resposta', models.CharField(choices=[('UNICA', 'Uma resposta'), ('MULTIPLA', 'Múltiplas respostas'), ('ESCALA', 'Escala'), ('NUMERO', 'Número'), ('TEXTO', 'Texto livre')], default='UNICA', max_length=20)),
                ('nr_peso', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('nr_minimo', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('nr_maximo', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('nr_ordem', models.PositiveIntegerField(default=0)),
                ('sn_obrigatoria', models.BooleanField(default=True)),
                ('sn_ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pesquisa_pergunta',
                'ordering': ('nr_ordem', 'cd_pergunta_pesquisa'),
            },
        ),
        migrations.CreateModel(
            name='OpcaoRespostaPesquisa',
            fields=[
                ('cd_opcao_resposta_pesquisa', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_resposta', models.CharField(max_length=300)),
                ('nr_valor', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('nr_ordem', models.PositiveIntegerField(default=0)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('cd_pergunta_pesquisa', models.ForeignKey(db_column='cd_pergunta_pesquisa', on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='pesquisas.perguntapesquisa')),
            ],
            options={
                'db_table': 'pesquisa_opcao_resposta',
                'ordering': ('nr_ordem', 'cd_opcao_resposta_pesquisa'),
            },
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('cd_pesquisa', models.BigAutoField(primary_key=True, serialize=False)),
                ('cd_token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nm_pesquisa', models.CharField(max_length=180)),
                ('ds_descricao', models.TextField(blank=True)),
                ('tp_pesquisa', models.CharField(choices=[('SATISFACAO', 'Satisfação'), ('CLIMA', 'Clima organizacional'), ('AVALIACAO', 'Avaliação'), ('CHECKLIST', 'Checklist'), ('OUTRA', 'Outra')], default='SATISFACAO', max_length=20)),
                ('tp_calculo', models.CharField(choices=[('SOMA', 'Soma ponderada'), ('MEDIA', 'Média ponderada'), ('PERCENTUAL', 'Percentual do total possível')], default='MEDIA', max_length=20)),
                ('sn_anonima', models.BooleanField(default=True)),
                ('sn_publica', models.BooleanField(default=True)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('dh_inicio', models.DateTimeField(blank=True, null=True)),
                ('dh_fim', models.DateTimeField(blank=True, null=True)),
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
            ],
            options={
                'db_table': 'pesquisa',
                'ordering': ('nm_pesquisa',),
            },
        ),
        migrations.AddField(
            model_name='perguntapesquisa',
            name='cd_pesquisa',
            field=models.ForeignKey(db_column='cd_pesquisa', on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='pesquisas.pesquisa'),
        ),
        migrations.CreateModel(
            name='FaixaResultadoPesquisa',
            fields=[
                ('cd_faixa_resultado_pesquisa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nm_resultado', models.CharField(max_length=120)),
                ('nr_minimo', models.DecimalField(decimal_places=3, max_digits=12)),
                ('nr_maximo', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ds_mensagem', models.TextField()),
                ('ds_cor', models.CharField(default='#2563eb', max_length=20)),
                ('nr_ordem', models.PositiveIntegerField(default=0)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('cd_pesquisa', models.ForeignKey(db_column='cd_pesquisa', on_delete=django.db.models.deletion.CASCADE, related_name='faixas_resultado', to='pesquisas.pesquisa')),
            ],
            options={
                'db_table': 'pesquisa_faixa_resultado',
                'ordering': ('nr_ordem', 'nr_minimo'),
            },
        ),
        migrations.CreateModel(
            name='RespostaPesquisa',
            fields=[
                ('cd_resposta_pesquisa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nr_resultado', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('dh_resposta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cd_faixa_resultado', models.ForeignKey(blank=True, db_column='cd_faixa_resultado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pesquisas.faixaresultadopesquisa')),
                ('cd_pesquisa', models.ForeignKey(db_column='cd_pesquisa', on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='pesquisas.pesquisa')),
                ('cd_usuario', models.ForeignKey(blank=True, db_column='cd_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pesquisa_resposta',
                'ordering': ('-dh_resposta',),
            },
        ),
        migrations.CreateModel(
            name='ItemRespostaPesquisa',
            fields=[
                ('cd_item_resposta_pesquisa', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_resposta', models.TextField(blank=True)),
                ('nr_valor', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cd_opcao_resposta', models.ForeignKey(blank=True, db_column='cd_opcao_resposta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pesquisas.opcaorespostapesquisa')),
                ('cd_pergunta_pesquisa', models.ForeignKey(db_column='cd_pergunta_pesquisa', on_delete=django.db.models.deletion.PROTECT, to='pesquisas.perguntapesquisa')),
                ('cd_resposta_pesquisa', models.ForeignKey(db_column='cd_resposta_pesquisa', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pesquisas.respostapesquisa')),
            ],
            options={
                'db_table': 'pesquisa_resposta_item',
                'ordering': ('cd_pergunta_pesquisa__nr_ordem', 'cd_item_resposta_pesquisa'),
            },
        ),
        migrations.AddConstraint(
            model_name='pesquisa',
            constraint=models.UniqueConstraint(fields=('cd_empresa', 'nm_pesquisa'), name='pesquisa_empresa_nome_unico'),
        ),
    ]
