# Generated by Django 4.2.30 on 2026-06-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0004_paciente_cor_raca"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestador",
            name="ds_bairro",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_cidade",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_complemento",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_conselho",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_endereco",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_observacao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_celular",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_cep",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_conselho",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_cpf",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_endereco",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_telefone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="prestador",
            name="sg_conselho",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="prestador",
            name="sg_estado",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="prestador",
            name="tp_prestador",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
