# Generated by Django 4.2.30 on 2026-06-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_options_alter_empresa_table_and_more"),
        ("atendimento", "0005_prestador_ds_bairro_prestador_ds_cidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atendimento",
            fields=[
                (
                    "cd_atendimento",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("ds_status", models.CharField(default="ABERTO", max_length=30)),
                ("ds_anamnese", models.TextField(blank=True)),
                ("ds_conduta", models.TextField(blank=True)),
                ("dh_inicio", models.DateTimeField(auto_now_add=True)),
                ("dh_fim", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "atendimento",
                "ordering": ("-dh_inicio",),
            },
        ),
        migrations.CreateModel(
            name="PreAtendimento",
            fields=[
                (
                    "cd_pre_atendimento",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "nr_prioridade",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Emergência"),
                            (2, "Muito urgente"),
                            (3, "Urgente"),
                            (4, "Pouco urgente"),
                            (5, "Não urgente"),
                        ],
                        default=3,
                    ),
                ),
                ("ds_queixa_principal", models.TextField()),
                ("nr_pressao_arterial", models.CharField(blank=True, max_length=15)),
                (
                    "nr_frequencia_cardiaca",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "nr_frequencia_respiratoria",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "nr_saturacao",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "nr_temperatura",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "nr_peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "nr_altura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("ds_observacao", models.TextField(blank=True)),
                ("dh_classificacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "pre_atendimento",
                "ordering": ("nr_prioridade", "dh_classificacao"),
            },
        ),
        migrations.AddField(
            model_name="agendamento",
            name="ds_status",
            field=models.CharField(
                choices=[
                    ("AGENDADO", "Agendado"),
                    ("AGUARDANDO_PRE_ATENDIMENTO", "Aguardando pré-atendimento"),
                    ("AGUARDANDO_ATENDIMENTO", "Aguardando atendimento"),
                    ("EM_ATENDIMENTO", "Em atendimento"),
                    ("FINALIZADO", "Finalizado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="AGENDADO",
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="agendamento",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cd_agenda_profissional__isnull", False),
                    ("dh_agendamento__isnull", False),
                ),
                fields=("cd_agenda_profissional", "dh_agendamento"),
                name="agendamento_horario_unico",
            ),
        ),
        migrations.AddField(
            model_name="preatendimento",
            name="cd_agendamento",
            field=models.OneToOneField(
                blank=True,
                db_column="cd_agendamento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pre_atendimento",
                to="atendimento.agendamento",
            ),
        ),
        migrations.AddField(
            model_name="preatendimento",
            name="cd_empresa",
            field=models.ForeignKey(
                db_column="cd_empresa",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.AddField(
            model_name="preatendimento",
            name="cd_paciente",
            field=models.ForeignKey(
                db_column="cd_paciente",
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.paciente",
            ),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="cd_agendamento",
            field=models.OneToOneField(
                blank=True,
                db_column="cd_agendamento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="atendimento",
                to="atendimento.agendamento",
            ),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="cd_empresa",
            field=models.ForeignKey(
                db_column="cd_empresa",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="cd_paciente",
            field=models.ForeignKey(
                db_column="cd_paciente",
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.paciente",
            ),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="cd_pre_atendimento",
            field=models.OneToOneField(
                blank=True,
                db_column="cd_pre_atendimento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.preatendimento",
            ),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="cd_prestador",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_prestador",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.prestador",
            ),
        ),
    ]
