# Generated by Django 4.2.30 on 2026-06-18 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_empresa_cd_usuario_atualizacao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("atendimento", "0007_agendamento_cd_usuario_atualizacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="ds_plano",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="sn_encaixe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="sn_particular",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="cd_convenio",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_convenio",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.convenio",
            ),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="ds_destino",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="ds_diagnostico",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="ds_especialidade",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="ds_hipotese_diagnostica",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="ds_origem",
            field=models.CharField(
                choices=[
                    ("AGENDADO", "Agendado"),
                    ("DEMANDA_ESPONTANEA", "Demanda espontânea"),
                    ("ENCAIXE", "Encaixe"),
                    ("RETORNO", "Retorno"),
                    ("URGENCIA_EMERGENCIA", "Urgência/Emergência"),
                ],
                default="DEMANDA_ESPONTANEA",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="ds_plano",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="ds_tipo_atendimento",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="atendimento",
            name="ds_unidade_setor",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="preatendimento",
            name="cd_prestador_responsavel",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_prestador_responsavel",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classificacoes_realizadas",
                to="atendimento.prestador",
            ),
        ),
        migrations.AddField(
            model_name="preatendimento",
            name="dh_fim",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="preatendimento",
            name="dh_inicio",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="preatendimento",
            name="ds_cor_prioridade",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="preatendimento",
            name="ds_sintomas",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="ds_status",
            field=models.CharField(
                choices=[
                    ("AGENDADO", "Agendado"),
                    ("CONFIRMADO", "Confirmado"),
                    ("RECEPCIONADO", "Recepcionado"),
                    ("FALTOU", "Faltou"),
                    ("REAGENDADO", "Reagendado"),
                    ("AGUARDANDO_PRE_ATENDIMENTO", "Aguardando pré-atendimento"),
                    ("AGUARDANDO_ATENDIMENTO", "Aguardando atendimento"),
                    ("EM_ATENDIMENTO", "Em atendimento"),
                    ("FINALIZADO", "Finalizado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="AGENDADO",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="atendimento",
            name="ds_status",
            field=models.CharField(
                choices=[
                    ("ABERTO", "Aberto"),
                    ("AGUARDANDO_CLASSIFICACAO", "Aguardando classificação"),
                    ("AGUARDANDO_CONSULTA", "Aguardando consulta"),
                    ("EM_ATENDIMENTO", "Em atendimento"),
                    ("AGUARDANDO_EXAMES", "Aguardando exames"),
                    ("FINALIZADO", "Finalizado"),
                    ("ENCAMINHADO", "Encaminhado"),
                    ("INTERNADO", "Internado"),
                    ("ALTA", "Alta"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="ABERTO",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SolicitacaoExame",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_solicitacao_exame",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("ds_exame", models.CharField(max_length=180)),
                ("ds_justificativa", models.TextField(blank=True)),
                (
                    "ds_prioridade",
                    models.CharField(
                        choices=[
                            ("ROTINA", "Rotina"),
                            ("URGENTE", "Urgente"),
                            ("EMERGENCIA", "Emergência"),
                        ],
                        default="ROTINA",
                        max_length=20,
                    ),
                ),
                (
                    "ds_status",
                    models.CharField(
                        choices=[
                            ("SOLICITADO", "Solicitado"),
                            ("COLETADO", "Coletado"),
                            ("EM_ANALISE", "Em análise"),
                            ("LIBERADO", "Liberado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="SOLICITADO",
                        max_length=20,
                    ),
                ),
                (
                    "cd_atendimento",
                    models.ForeignKey(
                        db_column="cd_atendimento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitacoes_exames",
                        to="atendimento.atendimento",
                    ),
                ),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solicitacao_exame",
                "ordering": ("-dh_criacao",),
            },
        ),
        migrations.CreateModel(
            name="ResultadoExame",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_resultado_exame",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("ds_resultado", models.TextField(blank=True)),
                (
                    "ds_anexo",
                    models.FileField(blank=True, upload_to="resultados_exames/"),
                ),
                ("sn_liberado", models.BooleanField(default=False)),
                ("dh_liberacao", models.DateTimeField(blank=True, null=True)),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_solicitacao_exame",
                    models.OneToOneField(
                        db_column="cd_solicitacao_exame",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultado",
                        to="atendimento.solicitacaoexame",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resultado_exame",
            },
        ),
    ]
