# Generated by Django 4.2.30 on 2026-06-18 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0006_empresa_cd_usuario_atualizacao_and_more"),
        ("atendimento", "0009_seed_perfis_clinicos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescricao",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_prescricao",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("ds_prescricao", models.TextField()),
                ("ds_orientacoes", models.TextField(blank=True)),
                ("sn_ativa", models.BooleanField(default=True)),
                (
                    "cd_atendimento",
                    models.ForeignKey(
                        db_column="cd_atendimento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescricoes",
                        to="atendimento.atendimento",
                    ),
                ),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prescricao",
                "ordering": ("-dh_criacao",),
            },
        ),
        migrations.CreateModel(
            name="EvolucaoAtendimento",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_evolucao_atendimento",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("ds_evolucao", models.TextField()),
                (
                    "cd_atendimento",
                    models.ForeignKey(
                        db_column="cd_atendimento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evolucoes",
                        to="atendimento.atendimento",
                    ),
                ),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_prestador",
                    models.ForeignKey(
                        db_column="cd_prestador",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atendimento.prestador",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "evolucao_atendimento",
                "ordering": ("-dh_criacao",),
            },
        ),
    ]
