# Generated by Django 4.2.30 on 2026-06-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0012_cleanup_perfis_homologacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestador",
            name="cd_banco",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_bairro_comercial",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_cidade_comercial",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_complemento_comercial",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_endereco_comercial",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_especialidades",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_grau_instrucao",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_nacionalidade",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_naturalidade",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="prestador",
            name="dt_expedicao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nm_agencia",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nm_mae",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nm_pai",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_agencia",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_cartao_sus",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_celular_2",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_cep_comercial",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_conta",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_endereco_comercial",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_rg",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="prestador",
            name="sg_estado_comercial",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="prestador",
            name="tp_genero",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="prestador",
            name="tp_logradouro_comercial",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
