# Generated by Django 4.2.30 on 2026-06-19 11:53

from django.db import migrations, models


def suggest_provider_permissions(apps, schema_editor):
    Prestador = apps.get_model("atendimento", "Prestador")
    Prestador.objects.filter(tp_prestador="MEDICO").update(
        sn_permite_agenda=True,
        sn_permite_atendimento=True,
        sn_permite_prescricao=True,
    )
    Prestador.objects.filter(tp_prestador="ENFERMEIRO").update(
        sn_permite_agenda=True,
        sn_permite_atendimento=True,
        sn_permite_classificacao=True,
    )
    Prestador.objects.filter(tp_prestador="TECNICO_ENFERMAGEM").update(
        sn_permite_classificacao=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0014_migrate_provider_specialties"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestador",
            name="ds_chave_pix",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="prestador",
            name="ds_contato_principal",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nm_favorecido",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_digito_agencia",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_digito_conta",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="prestador",
            name="nr_documento_favorecido",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="prestador",
            name="sn_mesmo_endereco",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prestador",
            name="sn_permite_agenda",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prestador",
            name="sn_permite_atendimento",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prestador",
            name="sn_permite_classificacao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prestador",
            name="sn_permite_prescricao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prestador",
            name="tp_conta",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(suggest_provider_permissions, migrations.RunPython.noop),
    ]
