import apps.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from importlib import import_module

from django.conf import settings
from django.db import migrations, models

migracao_0022 = import_module("apps.atendimento.operacoes_migracao.operacao_0022")
migracao_0024 = import_module("apps.atendimento.operacoes_migracao.operacao_0024")
migracao_0027 = import_module("apps.atendimento.operacoes_migracao.operacao_0027")
migracao_0029 = import_module("apps.atendimento.operacoes_migracao.operacao_0029")
migracao_0030 = import_module("apps.atendimento.operacoes_migracao.operacao_0030")
migracao_0031 = import_module("apps.atendimento.operacoes_migracao.operacao_0031")

class Migration(migrations.Migration):

    replaces = [('atendimento', '0018_painel_chamada'), ('atendimento', '0019_atendimento_central'), ('atendimento', '0020_painel_chamada_config_fields'), ('atendimento', '0021_modelodocumento_documentoclinico'), ('atendimento', '0022_alter_modelodocumento_unique_together_and_more'), ('atendimento', '0023_agendagerada_horarioagenda_and_more'), ('atendimento', '0024_seed_agendamento_screens'), ('atendimento', '0025_agendaprofissional_cd_setor_atendimento_and_more'), ('atendimento', '0026_documentoclinico_ds_dados_formulario_and_more'), ('atendimento', '0027_cadastro_recepcao_atendimento'), ('atendimento', '0028_perfis_assistenciais_e_alta'), ('atendimento', '0029_seed_documentos_clinicos_demonstrativos'), ('atendimento', '0030_padronizar_documentos_clinicos'), ('atendimento', '0031_ajustar_cabecalho_clinico'), ('atendimento', '0032_alter_modelodocumento_tp_elemento')]

    dependencies = [
        ('accounts', '0011_setor_setorusuario'),
        ('atendimento', '0017_patient_provider_review'),
        ('core', '0023_seed_minimum_test_auxiliary_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PainelChamada',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_painel_chamada', models.BigAutoField(primary_key=True, serialize=False)),
                ('nm_painel', models.CharField(max_length=120)),
                ('nm_maquina', models.CharField(max_length=120)),
                ('tp_painel', models.CharField(choices=[('SALA', 'Sala'), ('CONSULTORIO', 'Consultório'), ('GUICHE', 'Guichê'), ('PAINEL', 'Painel')], default='PAINEL', max_length=20)),
                ('nr_referencia', models.CharField(blank=True, max_length=20)),
                ('ds_layout', models.CharField(default='padrao', max_length=40)),
                ('ds_tamanho', models.CharField(default='medio', max_length=20)),
                ('ds_cor', models.CharField(default='azul', max_length=20)),
                ('sn_voz', models.BooleanField(default=True)),
                ('ds_midia_url', models.CharField(blank=True, max_length=500)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'painel_chamada',
                'ordering': ('nm_painel',),
                'unique_together': {('cd_empresa', 'nm_maquina')},
            },
        ),
        migrations.CreateModel(
            name='PainelChamadaSetor',
            fields=[
                ('cd_painel_chamada_setor', models.BigAutoField(primary_key=True, serialize=False)),
                ('cd_painel_chamada', models.ForeignKey(db_column='cd_painel_chamada', on_delete=django.db.models.deletion.CASCADE, to='atendimento.painelchamada')),
                ('cd_setor', models.ForeignKey(db_column='cd_setor', on_delete=django.db.models.deletion.PROTECT, to='accounts.setor')),
            ],
            options={
                'db_table': 'painel_chamada_setor',
                'unique_together': {('cd_painel_chamada', 'cd_setor')},
            },
        ),
        migrations.CreateModel(
            name='ChamadaPainel',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_chamada_painel', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_local', models.CharField(blank=True, max_length=80)),
                ('ds_status', models.CharField(choices=[('CHAMADO', 'Chamado'), ('ATENDIDO', 'Atendido'), ('CANCELADO', 'Cancelado')], default='CHAMADO', max_length=20)),
                ('dh_chamada', models.DateTimeField(default=django.utils.timezone.now)),
                ('cd_atendimento', models.ForeignKey(db_column='cd_atendimento', on_delete=django.db.models.deletion.PROTECT, related_name='chamadas_painel', to='atendimento.atendimento')),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_painel_chamada', models.ForeignKey(blank=True, db_column='cd_painel_chamada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.painelchamada')),
                ('cd_setor', models.ForeignKey(db_column='cd_setor', on_delete=django.db.models.deletion.PROTECT, to='accounts.setor')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chamada_painel',
                'ordering': ('-dh_chamada',),
            },
        ),
        migrations.AddField(
            model_name='painelchamada',
            name='setores',
            field=models.ManyToManyField(blank=True, related_name='paineis_chamada', through='atendimento.PainelChamadaSetor', to='accounts.setor'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='ds_status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('RECEPCIONADO', 'Recepcionado'), ('ABERTO', 'Aberto'), ('AGUARDANDO_CLASSIFICACAO', 'Aguardando classificação'), ('EM_CLASSIFICACAO', 'Em classificação'), ('AGUARDANDO_CONSULTA', 'Aguardando consulta'), ('EM_ATENDIMENTO', 'Em atendimento'), ('AGUARDANDO_EXAMES', 'Aguardando exames'), ('RETORNO_EXAMES', 'Retorno de exames'), ('EM_OBSERVACAO', 'Em observação'), ('ALTA_MEDICA', 'Alta médica'), ('ALTA_HOSPITALAR', 'Alta hospitalar'), ('FINALIZADO', 'Finalizado'), ('ENCAMINHADO', 'Encaminhado'), ('INTERNADO', 'Internado'), ('ALTA', 'Alta'), ('CANCELADO', 'Cancelado'), ('EVADIU', 'Evadiu'), ('OBITO', 'Óbito')], default='ABERTO', max_length=40),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cd_setor_atual',
            field=models.ForeignKey(blank=True, db_column='cd_setor_atual', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.setor'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cd_usuario_cancelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dh_alta_hospitalar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dh_alta_medica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dh_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dh_fim_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dh_fim_classificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dh_inicio_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dh_inicio_classificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='dh_recepcao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_motivo_atendimento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_motivo_cancelamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_observacao_recepcao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_procedimento_principal',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_queixa_principal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='sn_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AtendimentoFluxo',
            fields=[
                ('cd_atendimento_fluxo', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_status_anterior', models.CharField(blank=True, max_length=40)),
                ('ds_status_novo', models.CharField(max_length=40)),
                ('dh_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('ds_observacao', models.TextField(blank=True)),
                ('ds_origem', models.CharField(blank=True, max_length=80)),
                ('cd_atendimento', models.ForeignKey(db_column='cd_atendimento', on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='atendimento.atendimento')),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_prestador', models.ForeignKey(blank=True, db_column='cd_prestador', null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.prestador')),
                ('cd_setor', models.ForeignKey(blank=True, db_column='cd_setor', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.setor')),
                ('cd_usuario', models.ForeignKey(blank=True, db_column='cd_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'atendimento_fluxo',
                'ordering': ('-dh_evento',),
            },
        ),
        migrations.CreateModel(
            name='AtendimentoPrestador',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_atendimento_prestador', models.BigAutoField(primary_key=True, serialize=False)),
                ('tp_papel', models.CharField(choices=[('MEDICO', 'Médico'), ('ENFERMAGEM', 'Enfermagem'), ('LABORATORIO', 'Laboratório'), ('FISIOTERAPIA', 'Fisioterapia'), ('NUTRICAO', 'Nutrição'), ('PSICOLOGIA', 'Psicologia'), ('OUTRO', 'Outro profissional')], default='MEDICO', max_length=30)),
                ('dh_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('dh_fim', models.DateTimeField(blank=True, null=True)),
                ('sn_responsavel_principal', models.BooleanField(default=False)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('cd_atendimento', models.ForeignKey(db_column='cd_atendimento', on_delete=django.db.models.deletion.CASCADE, related_name='prestadores_vinculados', to='atendimento.atendimento')),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_prestador', models.ForeignKey(db_column='cd_prestador', on_delete=django.db.models.deletion.PROTECT, to='atendimento.prestador')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'atendimento_prestador',
                'ordering': ('-sn_responsavel_principal', 'dh_inicio'),
            },
        ),
        migrations.CreateModel(
            name='AtendimentoProcedimento',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_atendimento_procedimento', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_procedimento', models.CharField(max_length=160)),
                ('nr_quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('vl_procedimento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dh_lancamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('sn_principal', models.BooleanField(default=False)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('cd_atendimento', models.ForeignKey(db_column='cd_atendimento', on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='atendimento.atendimento')),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_prestador_executante', models.ForeignKey(blank=True, db_column='cd_prestador_executante', null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.prestador')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_lancamento', models.ForeignKey(blank=True, db_column='cd_usuario_lancamento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'atendimento_procedimento',
                'ordering': ('-sn_principal', '-dh_lancamento'),
            },
        ),
        migrations.AddField(
            model_name='painelchamada',
            name='ds_descricao',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='painelchamada',
            name='ds_local_exibicao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='painelchamada',
            name='ds_mensagem_padrao',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='painelchamada',
            name='nr_tempo_exibicao',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='painelchamada',
            name='ds_prioridade_visual',
            field=models.CharField(default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='painelchamada',
            name='ds_observacao',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_modelo_documento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nm_modelo', models.CharField(max_length=140)),
                ('tp_documento', models.CharField(choices=[('COMPROVANTE_AGENDAMENTO', 'Comprovante de agendamento'), ('FICHA_ATENDIMENTO', 'Ficha de atendimento'), ('PRESCRICAO', 'Prescrição'), ('SOLICITACAO_EXAME', 'Solicitação de exame'), ('EVOLUCAO', 'Evolução'), ('RESUMO_ALTA', 'Resumo de alta'), ('RECEITUARIO', 'Receituário'), ('ATESTADO', 'Atestado'), ('ENCAMINHAMENTO', 'Encaminhamento'), ('ADMINISTRATIVO', 'Administrativo')], max_length=40)),
                ('ds_cabecalho', models.TextField(blank=True)),
                ('ds_corpo', models.TextField(blank=True)),
                ('ds_rodape', models.TextField(blank=True)),
                ('ds_variaveis', models.JSONField(blank=True, default=list)),
                ('ds_campos_bloqueados', models.JSONField(blank=True, default=list)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('cd_empresa', models.ForeignKey(blank=True, db_column='cd_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('cd_cabecalho', models.ForeignKey(blank=True, db_column='cd_cabecalho', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_cabecalho', to='atendimento.modelodocumento')),
                ('cd_rodape', models.ForeignKey(blank=True, db_column='cd_rodape', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_rodape', to='atendimento.modelodocumento')),
                ('cd_versao_anterior', models.ForeignKey(blank=True, db_column='cd_versao_anterior', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versoes_seguintes', to='atendimento.modelodocumento')),
                ('ds_alteracoes_versao', models.CharField(blank=True, max_length=500)),
                ('ds_css_impressao', models.TextField(blank=True)),
                ('ds_css_tela', models.TextField(blank=True)),
                ('ds_html_impressao', models.TextField(blank=True)),
                ('ds_html_tela', models.TextField(blank=True)),
                ('ds_projeto_impressao', models.JSONField(blank=True, default=dict)),
                ('ds_projeto_tela', models.JSONField(blank=True, default=dict)),
                ('nr_versao', models.PositiveIntegerField(default=1)),
                ('sn_editavel', models.BooleanField(default=True)),
                ('sn_sistema', models.BooleanField(default=False)),
                ('sn_versao_atual', models.BooleanField(default=True)),
                ('tp_elemento', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('CABECALHO', 'Cabeçalho'), ('RODAPE', 'Rodapé')], default='DOCUMENTO', max_length=20)),
            ],
            options={
                'db_table': 'modelo_documento',
                'ordering': ('tp_documento', 'nm_modelo'),
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_documento_clinico', models.BigAutoField(primary_key=True, serialize=False)),
                ('tp_documento', models.CharField(max_length=40)),
                ('ds_titulo', models.CharField(max_length=160)),
                ('ds_conteudo', models.TextField(blank=True)),
                ('ds_campos_bloqueados', models.JSONField(blank=True, default=dict)),
                ('ds_status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('FINALIZADO', 'Finalizado'), ('ASSINADO', 'Assinado'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('dh_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dh_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('dh_assinatura', models.DateTimeField(blank=True, null=True)),
                ('dh_cancelamento', models.DateTimeField(blank=True, null=True)),
                ('cd_atendimento', models.ForeignKey(db_column='cd_atendimento', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='atendimento.atendimento')),
                ('cd_documento_origem', models.ForeignKey(blank=True, db_column='cd_documento_origem', null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento.documentoclinico')),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_emissor', models.ForeignKey(blank=True, db_column='cd_usuario_emissor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_emitidos', to=settings.AUTH_USER_MODEL)),
                ('cd_modelo_documento', models.ForeignKey(blank=True, db_column='cd_modelo_documento', null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.modelodocumento')),
            ],
            options={
                'db_table': 'documento_clinico',
                'ordering': ('-dh_emissao',),
            },
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='dt_fim',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='dt_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='PastaDocumento',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_pasta_documento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nm_pasta', models.CharField(max_length=120)),
                ('tp_pasta', models.CharField(choices=[('GERAL', 'Geral'), ('CABECALHOS', 'Cabeçalhos'), ('RODAPES', 'Rodapés'), ('ADMISSAO', 'Documentos de admissão'), ('ALTA', 'Documentos de alta')], default='GERAL', max_length=20)),
                ('nr_ordem', models.PositiveIntegerField(default=0)),
                ('sn_sistema', models.BooleanField(default=False)),
                ('sn_editavel', models.BooleanField(default=True)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('cd_empresa', models.ForeignKey(blank=True, db_column='cd_empresa', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_pasta_pai', models.ForeignKey(blank=True, db_column='cd_pasta_pai', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subpastas', to='atendimento.pastadocumento')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pasta_documento',
                'ordering': ('nr_ordem', 'nm_pasta'),
            },
        ),
        migrations.AddField(
            model_name='modelodocumento',
            name='cd_pasta',
            field=models.ForeignKey(blank=True, db_column='cd_pasta', null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.pastadocumento'),
        ),
        migrations.RunPython(
            code=migracao_0022.preparar_vigencias_e_pastas,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='modelodocumento',
            constraint=models.UniqueConstraint(fields=('cd_empresa', 'tp_documento', 'nm_modelo', 'nr_versao'), name='modelo_documento_versao_unica'),
        ),
        migrations.AddConstraint(
            model_name='pastadocumento',
            constraint=models.UniqueConstraint(fields=('cd_empresa', 'cd_pasta_pai', 'nm_pasta'), name='pasta_documento_unica'),
        ),
        migrations.CreateModel(
            name='AgendaGerada',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_agenda_gerada', models.BigAutoField(primary_key=True, serialize=False)),
                ('dt_inicio', models.DateField()),
                ('dt_fim', models.DateField()),
                ('ds_status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PARCIAL', 'Parcialmente cancelada'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=20)),
                ('ds_observacao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'agenda_gerada',
                'ordering': ('-dt_inicio', 'cd_escala__cd_prestador__nm_prestador'),
            },
        ),
        migrations.CreateModel(
            name='HorarioAgenda',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_horario_agenda', models.BigAutoField(primary_key=True, serialize=False)),
                ('dh_inicio', models.DateTimeField()),
                ('dh_fim', models.DateTimeField()),
                ('ds_status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('AGENDADO', 'Agendado'), ('CANCELADO', 'Cancelado')], default='DISPONIVEL', max_length=20)),
                ('ds_motivo_cancelamento', models.CharField(blank=True, max_length=240)),
            ],
            options={
                'db_table': 'horario_agenda',
                'ordering': ('dh_inicio',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='agendamento_horario_unico',
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='ds_dias_semana',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='sn_atende_feriado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendagerada',
            name='cd_empresa',
            field=models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa'),
        ),
        migrations.AddField(
            model_name='agendagerada',
            name='cd_escala',
            field=models.ForeignKey(db_column='cd_escala', on_delete=django.db.models.deletion.PROTECT, related_name='agendas_geradas', to='atendimento.agendaprofissional'),
        ),
        migrations.AddField(
            model_name='agendagerada',
            name='cd_usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendagerada',
            name='cd_usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horarioagenda',
            name='cd_agenda_gerada',
            field=models.ForeignKey(db_column='cd_agenda_gerada', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='atendimento.agendagerada'),
        ),
        migrations.AddField(
            model_name='horarioagenda',
            name='cd_empresa',
            field=models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa'),
        ),
        migrations.AddField(
            model_name='horarioagenda',
            name='cd_escala',
            field=models.ForeignKey(db_column='cd_escala', on_delete=django.db.models.deletion.PROTECT, to='atendimento.agendaprofissional'),
        ),
        migrations.AddField(
            model_name='horarioagenda',
            name='cd_prestador',
            field=models.ForeignKey(db_column='cd_prestador', on_delete=django.db.models.deletion.PROTECT, to='atendimento.prestador'),
        ),
        migrations.AddField(
            model_name='horarioagenda',
            name='cd_usuario_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horarioagenda',
            name='cd_usuario_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cd_horario_agenda',
            field=models.ForeignKey(blank=True, db_column='cd_horario_agenda', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='atendimento.horarioagenda'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('cd_agenda_profissional__isnull', False), ('dh_agendamento__isnull', False), models.Q(('ds_status', 'CANCELADO'), _negated=True)), fields=('cd_agenda_profissional', 'dh_agendamento'), name='agendamento_horario_unico'),
        ),
        migrations.AddConstraint(
            model_name='horarioagenda',
            constraint=models.UniqueConstraint(condition=models.Q(('ds_status', 'CANCELADO'), _negated=True), fields=('cd_empresa', 'cd_prestador', 'dh_inicio'), name='horario_agenda_prestador_unico'),
        ),
        migrations.RunPython(
            code=migracao_0024.cadastrar_telas_agendamento,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='cd_setor_atendimento',
            field=models.ForeignKey(blank=True, db_column='cd_setor_atendimento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='accounts.setor'),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='convenios',
            field=models.ManyToManyField(blank=True, db_table='escala_convenio', related_name='escalas', to='atendimento.convenio'),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='ds_especialidade',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='ds_tipo_agendamento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='qt_encaixes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='qt_horarios_dia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='tp_escala',
            field=models.CharField(default='AMBULATORIAL', max_length=40),
        ),
        migrations.AddField(
            model_name='agendaprofissional',
            name='tp_horario',
            field=models.CharField(choices=[('HORA_MARCADA', 'Hora marcada'), ('HORARIO_CHEGADA', 'Horário de chegada')], default='HORA_MARCADA', max_length=30),
        ),
        migrations.AddField(
            model_name='documentoclinico',
            name='ds_dados_formulario',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='modelodocumento',
            name='tp_elemento',
            field=models.CharField(choices=[('DOCUMENTO', 'Documento'), ('CABECALHO', 'Cabeçalho'), ('RODAPE', 'Rodapé'), ('CAMPO', 'Campo reutilizável')], default='DOCUMENTO', max_length=20),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_cbo_prestador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_cid',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_local_procedencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_meio_transporte',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_recepcao_origem',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_subplano',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='nr_senha_chamada',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='sn_retorno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='sn_visita',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ResponsavelAtendimento',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_responsavel_atendimento', models.BigAutoField(primary_key=True, serialize=False)),
                ('ds_parentesco', models.CharField(blank=True, max_length=80)),
                ('nm_responsavel', models.CharField(blank=True, max_length=160)),
                ('tp_estado_civil', models.CharField(blank=True, max_length=80)),
                ('nr_identidade', models.CharField(blank=True, max_length=30)),
                ('ds_orgao_emissor', models.CharField(blank=True, max_length=30)),
                ('dt_expedicao', models.DateField(blank=True, null=True)),
                ('nr_cpf', models.CharField(blank=True, max_length=14, validators=[apps.core.validators.validate_cpf])),
                ('ds_profissao', models.CharField(blank=True, max_length=120)),
                ('ds_nacionalidade', models.CharField(blank=True, max_length=120)),
                ('nr_celular', models.CharField(blank=True, max_length=20)),
                ('sn_mesmo_endereco_paciente', models.BooleanField(default=False)),
                ('sg_estado', models.CharField(blank=True, max_length=2)),
                ('ds_cidade', models.CharField(blank=True, max_length=120)),
                ('tp_logradouro', models.CharField(blank=True, max_length=80)),
                ('ds_endereco', models.CharField(blank=True, max_length=180)),
                ('nr_endereco', models.CharField(blank=True, max_length=20)),
                ('ds_complemento', models.CharField(blank=True, max_length=120)),
                ('ds_bairro', models.CharField(blank=True, max_length=120)),
                ('cd_atendimento', models.OneToOneField(db_column='cd_atendimento', on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='atendimento.atendimento')),
                ('cd_cep', models.ForeignKey(blank=True, db_column='cd_cep', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.cep')),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responsavel_atendimento',
            },
        ),
        migrations.RunPython(
            code=migracao_0027.seed_auxiliares,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='atendimento',
            name='ds_motivo_alta',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PerfilAssistencial',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_perfil_assistencial', models.BigAutoField(primary_key=True, serialize=False)),
                ('nm_perfil', models.CharField(max_length=120)),
                ('ds_descricao', models.CharField(blank=True, max_length=300)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('tipos_prestador', models.JSONField(blank=True, default=list)),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_assistencial',
                'ordering': ('nm_perfil',),
                'unique_together': {('cd_empresa', 'nm_perfil')},
            },
        ),
        migrations.CreateModel(
            name='ItemMenuAssistencial',
            fields=[
                ('dh_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dh_atualizacao', models.DateTimeField(auto_now=True)),
                ('cd_item_menu_assistencial', models.BigAutoField(primary_key=True, serialize=False)),
                ('nm_item', models.CharField(max_length=120)),
                ('ds_icone', models.CharField(blank=True, max_length=40)),
                ('nr_ordem', models.PositiveSmallIntegerField(default=0)),
                ('tp_item', models.CharField(choices=[('GRUPO', 'Grupo'), ('ACAO', 'Ação do sistema'), ('DOCUMENTO', 'Modelo de documento'), ('LINK_EXTERNO', 'Link externo'), ('ANCORA', 'Seção da ficha')], default='ACAO', max_length=20)),
                ('ds_acao', models.CharField(blank=True, max_length=60)),
                ('ds_url', models.CharField(blank=True, max_length=500)),
                ('sn_privado', models.BooleanField(default=False)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('cd_empresa', models.ForeignKey(db_column='cd_empresa', on_delete=django.db.models.deletion.PROTECT, to='accounts.empresa')),
                ('cd_item_pai', models.ForeignKey(blank=True, db_column='cd_item_pai', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='atendimento.itemmenuassistencial')),
                ('cd_modelo_documento', models.ForeignKey(blank=True, db_column='cd_modelo_documento', null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.modelodocumento')),
                ('cd_perfil_assistencial', models.ForeignKey(db_column='cd_perfil_assistencial', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='atendimento.perfilassistencial')),
                ('cd_usuario_atualizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_atualizados', to=settings.AUTH_USER_MODEL)),
                ('cd_usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item_menu_assistencial',
                'ordering': ('nr_ordem', 'nm_item'),
            },
        ),
        migrations.RunPython(
            code=migracao_0029.cadastrar_documentos,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=migracao_0030.padronizar_documentos,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(
            code=migracao_0031.ajustar_cabecalho,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='modelodocumento',
            name='tp_elemento',
            field=models.CharField(choices=[('DOCUMENTO', 'Documento'), ('CABECALHO', 'Cabeçalho'), ('RODAPE', 'Rodapé'), ('CAMPO', 'Campo reutilizável'), ('VARIAVEL', 'Variável personalizada'), ('BLOCO', 'Bloco reutilizável')], default='DOCUMENTO', max_length=20),
        ),
    ]
