# Generated by Django 5.1.4 on 2026-06-26 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_setor_setorusuario"),
        ("atendimento", "0020_painel_chamada_config_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloDocumento",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_modelo_documento",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nm_modelo", models.CharField(max_length=140)),
                (
                    "tp_documento",
                    models.CharField(
                        choices=[
                            ("COMPROVANTE_AGENDAMENTO", "Comprovante de agendamento"),
                            ("FICHA_ATENDIMENTO", "Ficha de atendimento"),
                            ("PRESCRICAO", "Prescrição"),
                            ("SOLICITACAO_EXAME", "Solicitação de exame"),
                            ("EVOLUCAO", "Evolução"),
                            ("RESUMO_ALTA", "Resumo de alta"),
                            ("RECEITUARIO", "Receituário"),
                            ("ATESTADO", "Atestado"),
                            ("ENCAMINHAMENTO", "Encaminhamento"),
                            ("ADMINISTRATIVO", "Administrativo"),
                        ],
                        max_length=40,
                    ),
                ),
                ("ds_cabecalho", models.TextField(blank=True)),
                ("ds_corpo", models.TextField(blank=True)),
                ("ds_rodape", models.TextField(blank=True)),
                ("ds_variaveis", models.JSONField(blank=True, default=list)),
                ("ds_campos_bloqueados", models.JSONField(blank=True, default=list)),
                ("sn_ativo", models.BooleanField(default=True)),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "modelo_documento",
                "ordering": ("tp_documento", "nm_modelo"),
                "unique_together": {("cd_empresa", "tp_documento", "nm_modelo")},
            },
        ),
        migrations.CreateModel(
            name="DocumentoClinico",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_documento_clinico",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("tp_documento", models.CharField(max_length=40)),
                ("ds_titulo", models.CharField(max_length=160)),
                ("ds_conteudo", models.TextField(blank=True)),
                ("ds_campos_bloqueados", models.JSONField(blank=True, default=dict)),
                (
                    "ds_status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("FINALIZADO", "Finalizado"),
                            ("ASSINADO", "Assinado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RASCUNHO",
                        max_length=20,
                    ),
                ),
                ("dh_emissao", models.DateTimeField(default=django.utils.timezone.now)),
                ("dh_finalizacao", models.DateTimeField(blank=True, null=True)),
                ("dh_assinatura", models.DateTimeField(blank=True, null=True)),
                ("dh_cancelamento", models.DateTimeField(blank=True, null=True)),
                (
                    "cd_atendimento",
                    models.ForeignKey(
                        db_column="cd_atendimento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="atendimento.atendimento",
                    ),
                ),
                (
                    "cd_documento_origem",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_documento_origem",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="atendimento.documentoclinico",
                    ),
                ),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_emissor",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_usuario_emissor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_emitidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_modelo_documento",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_modelo_documento",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="atendimento.modelodocumento",
                    ),
                ),
            ],
            options={
                "db_table": "documento_clinico",
                "ordering": ("-dh_emissao",),
            },
        ),
    ]
