# Generated by Django 5.0.14 on 2026-06-28 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_setor_setorusuario"),
        ("atendimento", "0022_alter_modelodocumento_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgendaGerada",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_agenda_gerada",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("dt_inicio", models.DateField()),
                ("dt_fim", models.DateField()),
                (
                    "ds_status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("PARCIAL", "Parcialmente cancelada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ATIVA",
                        max_length=20,
                    ),
                ),
                ("ds_observacao", models.TextField(blank=True)),
            ],
            options={
                "db_table": "agenda_gerada",
                "ordering": ("-dt_inicio", "cd_escala__cd_prestador__nm_prestador"),
            },
        ),
        migrations.CreateModel(
            name="HorarioAgenda",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_horario_agenda",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("dh_inicio", models.DateTimeField()),
                ("dh_fim", models.DateTimeField()),
                (
                    "ds_status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("AGENDADO", "Agendado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                    ),
                ),
                (
                    "ds_motivo_cancelamento",
                    models.CharField(blank=True, max_length=240),
                ),
            ],
            options={
                "db_table": "horario_agenda",
                "ordering": ("dh_inicio",),
            },
        ),
        migrations.RemoveConstraint(
            model_name="agendamento",
            name="agendamento_horario_unico",
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="ds_dias_semana",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="sn_atende_feriado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agendagerada",
            name="cd_empresa",
            field=models.ForeignKey(
                db_column="cd_empresa",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.AddField(
            model_name="agendagerada",
            name="cd_escala",
            field=models.ForeignKey(
                db_column="cd_escala",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendas_geradas",
                to="atendimento.agendaprofissional",
            ),
        ),
        migrations.AddField(
            model_name="agendagerada",
            name="cd_usuario_atualizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_atualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agendagerada",
            name="cd_usuario_criacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="horarioagenda",
            name="cd_agenda_gerada",
            field=models.ForeignKey(
                db_column="cd_agenda_gerada",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios",
                to="atendimento.agendagerada",
            ),
        ),
        migrations.AddField(
            model_name="horarioagenda",
            name="cd_empresa",
            field=models.ForeignKey(
                db_column="cd_empresa",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.AddField(
            model_name="horarioagenda",
            name="cd_escala",
            field=models.ForeignKey(
                db_column="cd_escala",
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.agendaprofissional",
            ),
        ),
        migrations.AddField(
            model_name="horarioagenda",
            name="cd_prestador",
            field=models.ForeignKey(
                db_column="cd_prestador",
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.prestador",
            ),
        ),
        migrations.AddField(
            model_name="horarioagenda",
            name="cd_usuario_atualizacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_atualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="horarioagenda",
            name="cd_usuario_criacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="cd_horario_agenda",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_horario_agenda",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="atendimento.horarioagenda",
            ),
        ),
        migrations.AddConstraint(
            model_name="agendamento",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cd_agenda_profissional__isnull", False),
                    ("dh_agendamento__isnull", False),
                    models.Q(("ds_status", "CANCELADO"), _negated=True),
                ),
                fields=("cd_agenda_profissional", "dh_agendamento"),
                name="agendamento_horario_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="horarioagenda",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ds_status", "CANCELADO"), _negated=True),
                fields=("cd_empresa", "cd_prestador", "dh_inicio"),
                name="horario_agenda_prestador_unico",
            ),
        ),
    ]
