# Generated by Django 5.0.14 on 2026-06-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_setor_setorusuario"),
        ("atendimento", "0024_seed_agendamento_screens"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendaprofissional",
            name="cd_setor_atendimento",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_setor_atendimento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escalas",
                to="accounts.setor",
            ),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="convenios",
            field=models.ManyToManyField(
                blank=True,
                db_table="escala_convenio",
                related_name="escalas",
                to="atendimento.convenio",
            ),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="ds_especialidade",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="ds_tipo_agendamento",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="qt_encaixes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="qt_horarios_dia",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="tp_escala",
            field=models.CharField(default="AMBULATORIAL", max_length=40),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="tp_horario",
            field=models.CharField(
                choices=[
                    ("HORA_MARCADA", "Hora marcada"),
                    ("HORARIO_CHEGADA", "Horário de chegada"),
                ],
                default="HORA_MARCADA",
                max_length=30,
            ),
        ),
    ]
