# Generated by Django 5.0.14 on 2026-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0025_agendaprofissional_cd_setor_atendimento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoclinico",
            name="ds_dados_formulario",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="modelodocumento",
            name="tp_elemento",
            field=models.CharField(
                choices=[
                    ("DOCUMENTO", "Documento"),
                    ("CABECALHO", "Cabeçalho"),
                    ("RODAPE", "Rodapé"),
                    ("CAMPO", "Campo reutilizável"),
                ],
                default="DOCUMENTO",
                max_length=20,
            ),
        ),
    ]
