# Generated by Django 5.0.14 on 2026-06-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0031_ajustar_cabecalho_clinico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelodocumento",
            name="tp_elemento",
            field=models.CharField(
                choices=[
                    ("DOCUMENTO", "Documento"),
                    ("CABECALHO", "Cabeçalho"),
                    ("RODAPE", "Rodapé"),
                    ("CAMPO", "Campo reutilizável"),
                    ("VARIAVEL", "Variável personalizada"),
                    ("BLOCO", "Bloco reutilizável"),
                ],
                default="DOCUMENTO",
                max_length=20,
            ),
        ),
    ]
