# Generated by Django 5.0.14 on 2026-07-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0035_modelodocumento_configuracao_assinatura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelodocumento",
            name="tp_documento",
            field=models.CharField(
                choices=[
                    ("COMPROVANTE_AGENDAMENTO", "Comprovante de agendamento"),
                    ("FICHA_ATENDIMENTO", "Ficha de atendimento"),
                    ("ETIQUETA_ATENDIMENTO", "Etiqueta de atendimento"),
                    ("PRESCRICAO", "Prescrição"),
                    ("SOLICITACAO_EXAME", "Solicitação de exame"),
                    ("EVOLUCAO", "Evolução"),
                    ("RESUMO_ALTA", "Resumo de alta"),
                    ("RECEITUARIO", "Receituário"),
                    ("ATESTADO", "Atestado"),
                    ("ENCAMINHAMENTO", "Encaminhamento"),
                    ("ADMINISTRATIVO", "Administrativo"),
                ],
                max_length=40,
            ),
        ),
    ]
