# Generated by Django 5.0.14 on 2026-07-03 20:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrar_regras_e_telas(apps, schema_editor):
    Classe = apps.get_model("atendimento", "ClasseSenhaAtendimento")
    Regra = apps.get_model("atendimento", "RegraSubdivisaoSenha")
    for classe in Classe.objects.exclude(cd_tipo_senha_id=None):
        Regra.objects.get_or_create(
            cd_empresa_id=classe.cd_empresa_id,
            cd_tipo_senha_id=classe.cd_tipo_senha_id,
            cd_classe_senha_id=classe.pk,
            defaults={
                "nr_prioridade": classe.nr_prioridade,
                "nr_idade_minima": classe.nr_idade_minima,
                "nr_idade_maxima": classe.nr_idade_maxima,
                "sn_ativo": classe.sn_ativo,
            },
        )

    Module = apps.get_model("core", "Module")
    Screen = apps.get_model("core", "ScreenDefinition")
    Group = apps.get_model("auth", "Group")
    Papel = apps.get_model("accounts", "Papel")
    PapelModulo = apps.get_model("accounts", "PapelModulo")
    PapelTela = apps.get_model("accounts", "PapelTela")
    modulo, _ = Module.objects.get_or_create(
        code="TOTEM_SENHAS",
        defaults={"title": "Totem de Senhas", "active": True},
    )
    telas = [
        ("Configurar senhas", "totem-configurar-senhas", "atendimento:configurar-senhas", "formulario", 10),
        ("Classes", "totem-classes-senha", "atendimento:classes-senha", "formulario", 20),
        ("Protocolos", "totem-protocolos-senha", "atendimento:protocolos-senha", "formulario", 30),
    ]
    for titulo, slug, acesso, tipo, ordem in telas:
        tela, _ = Screen.objects.update_or_create(
            access_key=acesso,
            defaults={
                "module": modulo,
                "title": titulo,
                "slug": slug,
                "screen_type": tipo,
                "parent_label": "Tabelas" if ordem > 10 else "",
                "table_name": "",
                "allow_query": True,
                "allow_insert": True,
                "allow_update": True,
                "allow_delete": ordem > 10,
                "active": True,
                "order": ordem,
            },
        )
        for grupo in Group.objects.filter(name="TI"):
            papel, _ = Papel.objects.get_or_create(grupo=grupo)
            PapelModulo.objects.get_or_create(papel=papel, modulo=modulo)
            PapelTela.objects.get_or_create(papel=papel, tela=tela)


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0014_user_cd_usuario_atualizacao_user_cd_usuario_criacao_and_more",
        ),
        ("atendimento", "0038_integrar_senhas_paineis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classesenhaatendimento",
            name="ds_icone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="cd_agenda_profissional",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_escala",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.agendaprofissional",
            ),
        ),
        migrations.AlterField(
            model_name="agendaprofissional",
            name="cd_agenda_profissional",
            field=models.BigAutoField(
                db_column="cd_escala", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="agendaprofissional",
            name="ds_agenda",
            field=models.CharField(db_column="nm_escala", max_length=160),
        ),
        migrations.AlterField(
            model_name="classesenhaatendimento",
            name="cd_tipo_senha",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_tipo_senha",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="atendimento.tiposenhaatendimento",
            ),
        ),
        migrations.AlterModelTable(
            name="agendaprofissional",
            table="escala",
        ),
        migrations.CreateModel(
            name="ProtocoloSenhaAtendimento",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_protocolo_senha",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nm_protocolo", models.CharField(max_length=120)),
                ("ds_protocolo", models.CharField(blank=True, max_length=500)),
                ("sn_ativo", models.BooleanField(default=True)),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "protocolo_senha",
                "ordering": ("nm_protocolo",),
                "unique_together": {("cd_empresa", "nm_protocolo")},
            },
        ),
        migrations.AddField(
            model_name="tiposenhaatendimento",
            name="cd_protocolo",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_protocolo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tipos_senha",
                to="atendimento.protocolosenhaatendimento",
            ),
        ),
        migrations.CreateModel(
            name="RegraSubdivisaoSenha",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_regra_subdivisao",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nr_prioridade", models.PositiveSmallIntegerField(default=5)),
                (
                    "nr_idade_minima",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "nr_idade_maxima",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("ds_icone", models.CharField(blank=True, max_length=40)),
                ("sn_ativo", models.BooleanField(default=True)),
                (
                    "cd_classe_senha",
                    models.ForeignKey(
                        db_column="cd_classe_senha",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regras_subdivisao",
                        to="atendimento.classesenhaatendimento",
                    ),
                ),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_tipo_senha",
                    models.ForeignKey(
                        db_column="cd_tipo_senha",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras_subdivisao",
                        to="atendimento.tiposenhaatendimento",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "regra_subdivisao_senha",
                "ordering": ("nr_prioridade", "cd_classe_senha__nm_classe_senha"),
                "unique_together": {("cd_tipo_senha", "cd_classe_senha")},
            },
        ),
        migrations.RunPython(migrar_regras_e_telas, migrations.RunPython.noop),
    ]
