# Generated by Django 5.0.14 on 2026-08-02 13:56

import apps.atendimento.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0042_icones_maquinas_chamada_consolidada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexoclinico",
            name="ds_arquivo",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url=None,
                    location=pathlib.PureWindowsPath(
                        "C:/Users/bvictor/Documents/Git/Celeris/private_clinical_media"
                    ),
                ),
                upload_to=apps.atendimento.models.caminho_anexo_clinico,
            ),
        ),
    ]
