# Generated by Django 5.0.14 on 2026-08-14 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendimento", "0062_ordenar_cores_classificacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssinaturaDigitalDocumento",
            fields=[
                (
                    "cd_assinatura_digital",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("tp_finalidade", models.CharField(max_length=20)),
                (
                    "ds_status",
                    models.CharField(
                        choices=[
                            ("VALIDA", "Válida"),
                            ("FALHA", "Falha"),
                            ("REVOGADA", "Revogada"),
                        ],
                        default="VALIDA",
                        max_length=20,
                    ),
                ),
                ("ds_sujeito", models.CharField(max_length=500)),
                ("ds_emissor", models.CharField(max_length=500)),
                ("nr_serie", models.CharField(max_length=160)),
                ("ds_fingerprint_sha256", models.CharField(max_length=95)),
                ("ds_hash_pdf_assinado", models.CharField(max_length=64)),
                (
                    "dh_assinatura",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("ds_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ds_user_agent", models.CharField(blank=True, max_length=500)),
                ("ds_detalhes", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "assinatura_digital_documento",
                "ordering": ("-dh_assinatura",),
            },
        ),
        migrations.CreateModel(
            name="AuditoriaAssinaturaDigital",
            fields=[
                (
                    "cd_auditoria_assinatura",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("tp_evento", models.CharField(max_length=60)),
                ("ds_status", models.CharField(max_length=20)),
                ("ds_mensagem", models.CharField(blank=True, max_length=500)),
                ("ds_hash_pdf", models.CharField(blank=True, max_length=64)),
                ("ds_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ds_user_agent", models.CharField(blank=True, max_length=500)),
                ("ds_dados", models.JSONField(blank=True, default=dict)),
                (
                    "dh_evento",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "auditoria_assinatura_digital",
                "ordering": ("-dh_evento",),
            },
        ),
        migrations.CreateModel(
            name="VersaoDocumentoClinico",
            fields=[
                (
                    "cd_versao_documento_clinico",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nr_versao", models.PositiveIntegerField()),
                (
                    "ds_status",
                    models.CharField(
                        choices=[
                            ("FINALIZADO", "Finalizado"),
                            ("ASSINADO", "Assinado"),
                            ("FALHA", "Falha"),
                        ],
                        max_length=20,
                    ),
                ),
                ("arquivo_pdf", models.BinaryField()),
                ("ds_hash_sha256", models.CharField(db_index=True, max_length=64)),
                ("nr_tamanho_bytes", models.PositiveBigIntegerField()),
                ("nr_paginas", models.PositiveIntegerField(default=1)),
                (
                    "ds_mime_type",
                    models.CharField(default="application/pdf", max_length=80),
                ),
                ("ds_motivo_versao", models.CharField(blank=True, max_length=500)),
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "db_table": "versao_documento_clinico",
                "ordering": ("-nr_versao",),
            },
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="tp_finalidade_assinatura",
            field=models.CharField(
                choices=[
                    ("MEDICO", "Documento médico"),
                    ("ADMINISTRATIVO", "Documento administrativo"),
                    ("OUTRO", "Outro documento"),
                ],
                default="MEDICO",
                max_length=20,
            ),
        ),
    ]
