# Generated by Django 5.0.14 on 2026-08-14 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user_groups_alter_user_is_active_and_more"),
        ("atendimento", "0063_assinaturadigitaldocumento_and_more"),
        ("core", "0057_certificadodigitalempresa_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assinaturadigitaldocumento",
            name="cd_certificado_digital",
            field=models.ForeignKey(
                db_column="cd_certificado_digital",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assinaturas_documentos",
                to="core.certificadodigitalempresa",
            ),
        ),
        migrations.AddField(
            model_name="assinaturadigitaldocumento",
            name="cd_empresa",
            field=models.ForeignKey(
                db_column="cd_empresa",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.AddField(
            model_name="assinaturadigitaldocumento",
            name="cd_usuario_solicitante",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_usuario_solicitante",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assinaturas_digitais_solicitadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditoriaassinaturadigital",
            name="cd_certificado_digital",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_certificado_digital",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auditorias_assinatura",
                to="core.certificadodigitalempresa",
            ),
        ),
        migrations.AddField(
            model_name="auditoriaassinaturadigital",
            name="cd_documento_clinico",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_documento_clinico",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auditorias_assinatura",
                to="atendimento.documentoclinico",
            ),
        ),
        migrations.AddField(
            model_name="auditoriaassinaturadigital",
            name="cd_empresa",
            field=models.ForeignKey(
                db_column="cd_empresa",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.AddField(
            model_name="auditoriaassinaturadigital",
            name="cd_usuario",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_usuario",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="versaodocumentoclinico",
            name="cd_documento_clinico",
            field=models.ForeignKey(
                db_column="cd_documento_clinico",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versoes_finais",
                to="atendimento.documentoclinico",
            ),
        ),
        migrations.AddField(
            model_name="versaodocumentoclinico",
            name="cd_empresa",
            field=models.ForeignKey(
                db_column="cd_empresa",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.AddField(
            model_name="versaodocumentoclinico",
            name="cd_usuario_criacao",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_usuario_criacao",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versoes_documentos_clinicos_criadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="versaodocumentoclinico",
            name="cd_versao_anterior",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_versao_anterior",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versoes_seguintes",
                to="atendimento.versaodocumentoclinico",
            ),
        ),
        migrations.AddField(
            model_name="assinaturadigitaldocumento",
            name="cd_versao_documento",
            field=models.OneToOneField(
                db_column="cd_versao_documento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assinatura_digital",
                to="atendimento.versaodocumentoclinico",
            ),
        ),
        migrations.AddConstraint(
            model_name="versaodocumentoclinico",
            constraint=models.UniqueConstraint(
                fields=("cd_documento_clinico", "nr_versao"),
                name="versao_documento_clinico_unica",
            ),
        ),
    ]
