# Generated by Django 4.2.30 on 2026-06-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_seed_provider_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoPrestadorConselho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("tp_prestador", models.CharField(max_length=40, unique=True)),
                ("ds_conselho", models.CharField(max_length=20)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipo_prestador_conselho",
                "ordering": ("tp_prestador",),
            },
        ),
        migrations.AlterModelTable(
            name="module",
            table="modulo",
        ),
        migrations.AlterModelTable(
            name="screendefinition",
            table="definicao_tela",
        ),
        migrations.AlterModelTable(
            name="screenfield",
            table="campo_tela",
        ),
        migrations.AlterModelTable(
            name="tabelaauxiliarglobal",
            table="tabela_auxiliar",
        ),
        migrations.AlterModelTable(
            name="usermodule",
            table="modulo_usuario",
        ),
        migrations.AlterModelTable(
            name="valorauxiliarglobal",
            table="valor_auxiliar",
        ),
    ]
