# Generated by Django 4.2.30 on 2026-06-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_seed_idiomas"),
    ]

    operations = [
        migrations.AddField(
            model_name="screendefinition",
            name="access_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=220, null=True, unique=True
            ),
        ),
    ]
