# Generated by Codex

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_user_cd_usuario_atualizacao_user_cd_usuario_criacao_and_more"),
        ("core", "0029_seed_cids_motivos_alta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravaEdicao",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("cd_trava_edicao", models.BigAutoField(primary_key=True, serialize=False)),
                ("ds_recurso_tipo", models.CharField(max_length=80)),
                ("ds_recurso_id", models.CharField(max_length=120)),
                ("ds_recurso_titulo", models.CharField(blank=True, max_length=180)),
                ("ds_identificador_guia", models.CharField(blank=True, max_length=120)),
                ("dh_expiracao", models.DateTimeField()),
                ("nr_tentativas_bloqueadas", models.PositiveIntegerField(default=0)),
                ("ds_ultimo_usuario_bloqueado", models.CharField(blank=True, max_length=150)),
                ("dh_ultimo_bloqueio", models.DateTimeField(blank=True, null=True)),
                ("ds_liberacao", models.CharField(blank=True, max_length=220)),
                ("sn_ativa", models.BooleanField(default=True)),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travas_edicao",
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_usuario",
                    models.ForeignKey(
                        db_column="cd_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travas_edicao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trava_edicao",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.AddIndex(
            model_name="travaedicao",
            index=models.Index(fields=["cd_empresa", "ds_recurso_tipo", "ds_recurso_id", "sn_ativa"], name="trava_edica_cd_empr_5e5033_idx"),
        ),
        migrations.AddIndex(
            model_name="travaedicao",
            index=models.Index(fields=["dh_expiracao", "sn_ativa"], name="trava_edica_dh_expi_3d47a8_idx"),
        ),
        migrations.AddConstraint(
            model_name="travaedicao",
            constraint=models.UniqueConstraint(
                condition=models.Q(sn_ativa=True),
                fields=("cd_empresa", "ds_recurso_tipo", "ds_recurso_id"),
                name="uq_trava_edicao_recurso_ativo",
            ),
        ),
    ]
