# Generated by Django 5.0.14 on 2026-08-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_reorganizar_classificacao_e_chamadas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valorauxiliarglobal",
            name="ds_grupo",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name="valorauxiliarglobal",
            name="ds_valor",
            field=models.CharField(max_length=500),
        ),
    ]
