# Generated by Django 5.0.14 on 2026-08-10 22:56

from django.db import migrations, models


MODELOS_POR_TEMA = {
    "bairro": "Bairro",
    "banco": "Banco",
    "cbo": "Cbo",
    "cidade": "Cidade",
    "cids": "Cid",
    "cid": "Cid",
    "conselho_profissional": "ConselhoProfissional",
    "cor_raca": "CorRaca",
    "destino_atendimento": "DestinoAtendimento",
    "especialidade": "Especialidade",
    "estado": "Estado",
    "estado_civil": "EstadoCivil",
    "genero": "Genero",
    "grau_instrucao": "GrauInstrucao",
    "identidade_genero": "IdentidadeGenero",
    "idioma": "Idioma",
    "local_procedencia": "LocalProcedencia",
    "meio_comunicacao": "MeioComunicacao",
    "meio_transporte": "MeioTransporte",
    "motivo_alteracao": "MotivoAlteracao",
    "motivos_alta": "MotivoAlta",
    "motivo_alta": "MotivoAlta",
    "nacionalidade": "Nacionalidade",
    "naturalidade": "Naturalidade",
    "orgao_emissor": "OrgaoEmissor",
    "orientacao_sexual": "OrientacaoSexual",
    "origem": "Origem",
    "origem_recepcao": "OrigemRecepcao",
    "pais": "Pais",
    "parentesco": "Parentesco",
    "profissao": "Profissao",
    "raca_cor": "RacaCor",
    "religiao": "Religiao",
    "setor_exame": "SetorExame",
    "sexo": "Sexo",
    "tipo_identificador_pessoa": "TipoIdentificadorPessoa",
    "tipo_logradouro": "TipoLogradouro",
    "tipo_moradia": "TipoMoradia",
    "tipo_ocorrencia": "TipoOcorrencia",
    "tipo_prestador": "TipoPrestador",
    "tipo_sanguineo": "TipoSanguineo",
    "tipo_vinculo": "TipoVinculo",
    "vulnerabilidade_social": "VulnerabilidadeSocial",
}


def copiar_catalogos_por_tema(apps, schema_editor):
    ValorAuxiliarGlobal = apps.get_model("core", "ValorAuxiliarGlobal")
    valores = ValorAuxiliarGlobal.objects.select_related("cd_tabela_auxiliar_global")
    for valor in valores.iterator():
        nome_modelo = MODELOS_POR_TEMA.get(valor.cd_tabela_auxiliar_global.ds_tabela)
        if not nome_modelo:
            continue
        modelo = apps.get_model("core", nome_modelo)
        dados = {
            "cd_valor": valor.cd_valor,
            "ds_valor": valor.ds_valor,
            "ds_grupo": valor.ds_grupo,
            "sn_ativo": valor.sn_ativo,
        }
        if valor.cd_tabela_auxiliar_global.ds_tabela == "motivo_alteracao":
            modelo.objects.update_or_create(cd_item_catalogo=valor.pk, defaults=dados)
        else:
            codigo = dados.pop("cd_valor")
            modelo.objects.update_or_create(cd_valor=codigo, defaults=dados)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_tabelas_agendamento"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tabelaauxiliarglobal",
            table="catalogo_auxiliar_tema",
        ),
        migrations.AlterModelTable(
            name="valorauxiliarglobal",
            table="indice_catalogo_auxiliar",
        ),
        migrations.AlterModelTable(
            name="cep",
            table="ceps",
        ),
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bairros",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "bancos",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Cbo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cbos",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Cid",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cids",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cidades",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="ConselhoProfissional",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "conselhos_profissionais",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="CorRaca",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cores_racas",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="DestinoAtendimento",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "destinos_atendimento",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "especialidades",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "estados",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="EstadoCivil",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "estados_civis",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "generos",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="GrauInstrucao",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "graus_instrucao",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="IdentidadeGenero",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "identidades_genero",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Idioma",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "idiomas",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="LocalProcedencia",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "locais_procedencia",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="MeioComunicacao",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "meios_comunicacao",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="MeioTransporte",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "meios_transporte",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="MotivoAlta",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "motivos_alta",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="MotivoAlteracao",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "motivos_alteracao",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Nacionalidade",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "nacionalidades",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Naturalidade",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "naturalidades",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="OrgaoEmissor",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "orgaos_emissores",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="OrientacaoSexual",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "orientacoes_sexuais",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Origem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "origens",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="OrigemRecepcao",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "origens_recepcao",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "paises",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Parentesco",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "parentescos",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Profissao",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "profissoes",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="RacaCor",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "racas_cores",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Religiao",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "religioes",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="SetorExame",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "setores_exame",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="Sexo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "sexos",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="TipoIdentificadorPessoa",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_identificador_pessoa",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="TipoLogradouro",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_logradouro",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="TipoMoradia",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_moradia",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="TipoOcorrencia",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_ocorrencia",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="TipoPrestador",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_prestador",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="TipoSanguineo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_sanguineos",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="TipoVinculo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tipos_vinculo",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.CreateModel(
            name="VulnerabilidadeSocial",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_item_catalogo",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("cd_valor", models.CharField(max_length=40, unique=True)),
                ("ds_valor", models.CharField(max_length=500)),
                ("ds_grupo", models.CharField(blank=True, max_length=160)),
                ("sn_ativo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "vulnerabilidades_sociais",
                "ordering": ("ds_valor",),
            },
        ),
        migrations.RunPython(copiar_catalogos_por_tema, migrations.RunPython.noop),
    ]
