# Generated by Django 5.0.14 on 2026-08-14 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user_groups_alter_user_is_active_and_more"),
        ("core", "0056_ocultar_fila_classificacao_e_expor_escalas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificadoDigitalEmpresa",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_certificado_digital",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nm_certificado", models.CharField(max_length=160)),
                (
                    "tp_certificado",
                    models.CharField(
                        choices=[
                            ("INSTITUCIONAL", "Institucional"),
                            ("PROFISSIONAL", "Profissional"),
                        ],
                        default="INSTITUCIONAL",
                        max_length=20,
                    ),
                ),
                ("arquivo_criptografado", models.BinaryField()),
                ("arquivo_nonce", models.BinaryField(max_length=12)),
                ("senha_criptografada", models.BinaryField()),
                ("senha_nonce", models.BinaryField(max_length=12)),
                ("versao_chave", models.CharField(default="v1", max_length=40)),
                ("ds_sujeito", models.CharField(max_length=500)),
                ("ds_emissor", models.CharField(max_length=500)),
                ("nr_serie", models.CharField(max_length=160)),
                (
                    "ds_fingerprint_sha256",
                    models.CharField(db_index=True, max_length=95),
                ),
                ("nr_cpf_cnpj", models.CharField(blank=True, max_length=18)),
                ("dh_inicio_validade", models.DateTimeField()),
                ("dh_fim_validade", models.DateTimeField(db_index=True)),
                ("sn_assina_documentos_medicos", models.BooleanField(default=False)),
                (
                    "sn_assina_documentos_administrativos",
                    models.BooleanField(default=False),
                ),
                ("sn_assina_outros_documentos", models.BooleanField(default=False)),
                ("sn_ativo", models.BooleanField(db_index=True, default=True)),
                ("dh_ultima_validacao", models.DateTimeField(blank=True, null=True)),
                ("ds_ultima_validacao", models.CharField(blank=True, max_length=500)),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificados_digitais",
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_usuario_atualizacao",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados_digitais_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_usuario_criacao",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados_digitais_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_profissional",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_usuario_profissional",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificados_digitais_profissionais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "certificado_digital_empresa",
                "ordering": ("-sn_ativo", "dh_fim_validade", "nm_certificado"),
                "permissions": (
                    (
                        "gerenciar_certificados_digitais",
                        "Pode gerenciar certificados digitais",
                    ),
                    (
                        "testar_certificados_digitais",
                        "Pode testar certificados digitais",
                    ),
                    (
                        "consultar_auditoria_assinaturas",
                        "Pode consultar auditoria de assinaturas",
                    ),
                ),
            },
        ),
        migrations.AddConstraint(
            model_name="certificadodigitalempresa",
            constraint=models.UniqueConstraint(
                fields=("cd_empresa", "ds_fingerprint_sha256"),
                name="certificado_digital_fingerprint_empresa_unico",
            ),
        ),
    ]
