# Generated by Django 5.0.14 on 2026-08-14 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user_groups_alter_user_is_active_and_more"),
        ("core", "0058_navegacao_certificados_digitais"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditoriaCertificadoDigital",
            fields=[
                (
                    "cd_auditoria_certificado",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("tp_evento", models.CharField(max_length=40)),
                ("ds_resultado", models.CharField(max_length=20)),
                ("ds_mensagem", models.CharField(blank=True, max_length=500)),
                ("ds_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ds_user_agent", models.CharField(blank=True, max_length=500)),
                (
                    "dh_evento",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "cd_certificado_digital",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_certificado_digital",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias_administrativas",
                        to="core.certificadodigitalempresa",
                    ),
                ),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="auditorias_certificados_digitais",
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_usuario",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "auditoria_certificado_digital",
                "ordering": ("-dh_evento",),
            },
        ),
    ]
