"""
Países obtidos do Registro de Referência do IBGE.

Arquivo gerado automaticamente para a migration 0011.
Não editar nem substituir depois que a migration for publicada.
"""

PAISES: list[tuple[str, str]] = [
    ('AF', 'AFEGANISTÃO'),
    ('AL', 'ALBÂNIA'),
    ('DE', 'ALEMANHA'),
    ('AD', 'ANDORRA'),
    ('AO', 'ANGOLA'),
    ('AG', 'ANTÍGUA E BARBUDA'),
    ('AR', 'ARGENTINA'),
    ('DZ', 'ARGÉLIA'),
    ('AM', 'ARMÊNIA'),
    ('SA', 'ARÁBIA SAUDITA'),
    ('AU', 'AUSTRÁLIA'),
    ('AZ', 'AZERBAIJÃO'),
    ('BS', 'BAHAMAS'),
    ('BD', 'BANGLADESH'),
    ('BB', 'BARBADOS'),
    ('BH', 'BAREIN'),
    ('BY', 'BELARUS'),
    ('BZ', 'BELIZE'),
    ('BJ', 'BENIN'),
    ('BO', 'BOLÍVIA'),
    ('BW', 'BOTSUANA'),
    ('BR', 'BRASIL'),
    ('BN', 'BRUNEI'),
    ('BG', 'BULGÁRIA'),
    ('BF', 'BURKINA FASO'),
    ('BI', 'BURUNDI'),
    ('BT', 'BUTÃO'),
    ('BE', 'BÉLGICA'),
    ('BA', 'BÓSNIA E HERZEGOVINA'),
    ('CV', 'CABO VERDE'),
    ('CM', 'CAMARÕES'),
    ('KH', 'CAMBOJA'),
    ('CA', 'CANADÁ'),
    ('QA', 'CATAR'),
    ('KZ', 'CAZAQUISTÃO'),
    ('TD', 'CHADE'),
    ('CL', 'CHILE'),
    ('CN', 'CHINA'),
    ('CY', 'CHIPRE'),
    ('CO', 'COLÔMBIA'),
    ('KM', 'COMORES'),
    ('CI', 'COSTA DO MARFIM'),
    ('CR', 'COSTA RICA'),
    ('HR', 'CROÁCIA'),
    ('CU', 'CUBA'),
    ('DK', 'DINAMARCA'),
    ('DJ', 'DJIBOUTI'),
    ('DM', 'DOMINICA'),
    ('EG', 'EGITO'),
    ('SV', 'EL SALVADOR'),
    ('AE', 'EMIRADOS ÁRABES UNIDOS'),
    ('EC', 'EQUADOR'),
    ('ER', 'ERITREIA'),
    ('SK', 'ESLOVÁQUIA'),
    ('SI', 'ESLOVÊNIA'),
    ('ES', 'ESPANHA'),
    ('US', 'ESTADOS UNIDOS DA AMÉRICA'),
    ('EE', 'ESTÔNIA'),
    ('SZ', 'ESWATINI'),
    ('ET', 'ETIÓPIA'),
    ('FJ', 'FIJI'),
    ('PH', 'FILIPINAS'),
    ('FI', 'FINLÂNDIA'),
    ('FR', 'FRANÇA'),
    ('GA', 'GABÃO'),
    ('GH', 'GANA'),
    ('GE', 'GEÓRGIA'),
    ('GD', 'GRANADA'),
    ('GR', 'GRÉCIA'),
    ('GT', 'GUATEMALA'),
    ('GY', 'GUIANA'),
    ('GN', 'GUINÉ'),
    ('GQ', 'GUINÉ EQUATORIAL'),
    ('GW', 'GUINÉ-BISSAU'),
    ('GM', 'GÂMBIA'),
    ('HT', 'HAITI'),
    ('HN', 'HONDURAS'),
    ('HU', 'HUNGRIA'),
    ('MH', 'ILHAS MARSHALL'),
    ('SB', 'ILHAS SALOMÃO'),
    ('ID', 'INDONÉSIA'),
    ('IQ', 'IRAQUE'),
    ('IE', 'IRLANDA'),
    ('IR', 'IRÃ'),
    ('IS', 'ISLÂNDIA'),
    ('IL', 'ISRAEL'),
    ('IT', 'ITÁLIA'),
    ('YE', 'IÊMEN'),
    ('JM', 'JAMAICA'),
    ('JP', 'JAPÃO'),
    ('JO', 'JORDÂNIA'),
    ('KI', 'KIRIBATI'),
    ('KW', 'KUWAIT'),
    ('LA', 'LAOS'),
    ('LS', 'LESOTO'),
    ('LV', 'LETÔNIA'),
    ('LR', 'LIBÉRIA'),
    ('LI', 'LIECHTENSTEIN'),
    ('LT', 'LITUÂNIA'),
    ('LU', 'LUXEMBURGO'),
    ('LB', 'LÍBANO'),
    ('LY', 'LÍBIA'),
    ('MK', 'MACEDÔNIA DO NORTE'),
    ('MG', 'MADAGASCAR'),
    ('MW', 'MALAUÍ'),
    ('MV', 'MALDIVAS'),
    ('ML', 'MALI'),
    ('MT', 'MALTA'),
    ('MY', 'MALÁSIA'),
    ('MA', 'MARROCOS'),
    ('MR', 'MAURITÂNIA'),
    ('MU', 'MAURÍCIO'),
    ('MM', 'MIANMAR'),
    ('FM', 'MICRONÉSIA'),
    ('MD', 'MOLDÁVIA'),
    ('MN', 'MONGÓLIA'),
    ('ME', 'MONTENEGRO'),
    ('MZ', 'MOÇAMBIQUE'),
    ('MX', 'MÉXICO'),
    ('MC', 'MÔNACO'),
    ('NA', 'NAMÍBIA'),
    ('NR', 'NAURU'),
    ('NP', 'NEPAL'),
    ('NI', 'NICARÁGUA'),
    ('NE', 'NIGER'),
    ('NG', 'NIGÉRIA'),
    ('NO', 'NORUEGA'),
    ('NZ', 'NOVA ZELÂNDIA'),
    ('OM', 'OMÃ'),
    ('PW', 'PALAU'),
    ('PA', 'PANAMÁ'),
    ('PG', 'PAPUA NOVA GUINÉ'),
    ('PK', 'PAQUISTÃO'),
    ('PY', 'PARAGUAI'),
    ('NL', 'PAÍSES BAIXOS'),
    ('PE', 'PERU'),
    ('PL', 'POLÔNIA'),
    ('PT', 'PORTUGAL'),
    ('KG', 'QUIRGUISTÃO'),
    ('KE', 'QUÊNIA'),
    ('GB', 'REINO UNIDO'),
    ('CF', 'REPÚBLICA CENTRO-AFRICANA'),
    ('KR', 'REPÚBLICA DA COREIA'),
    ('CD', 'REPÚBLICA DEMOCRÁTICA DO CONGO'),
    ('CG', 'REPÚBLICA DO CONGO'),
    ('DO', 'REPÚBLICA DOMINICANA'),
    ('KP', 'REPÚBLICA POPULAR DEMOCRÁTICA DA COREIA'),
    ('CZ', 'REPÚBLICA TCHECA'),
    ('RO', 'ROMÊNIA'),
    ('RW', 'RUANDA'),
    ('RU', 'RÚSSIA (FEDERAÇÃO RUSSA)'),
    ('WS', 'SAMOA'),
    ('SM', 'SAN MARINO'),
    ('LC', 'SANTA LÚCIA'),
    ('SC', 'SEICHELLES'),
    ('SN', 'SENEGAL'),
    ('SL', 'SERRA LEOA'),
    ('SG', 'SINGAPURA'),
    ('SO', 'SOMÁLIA'),
    ('LK', 'SRI LANKA'),
    ('SD', 'SUDÃO'),
    ('SS', 'SUDÃO DO SUL'),
    ('SR', 'SURINAME'),
    ('SE', 'SUÉCIA'),
    ('CH', 'SUÍÇA'),
    ('KN', 'SÃO CRISTÓVÃO E NEVIS'),
    ('ST', 'SÃO TOMÉ E PRÍNCIPE'),
    ('VC', 'SÃO VICENTE E GRANADINAS'),
    ('RS', 'SÉRVIA'),
    ('SY', 'SÍRIA'),
    ('TJ', 'TADJIQUISTÃO'),
    ('TH', 'TAILÂNDIA'),
    ('TZ', 'TANZÂNIA'),
    ('TL', 'TIMOR-LESTE'),
    ('TG', 'TOGO'),
    ('TO', 'TONGA'),
    ('TT', 'TRINIDAD E TOBAGO'),
    ('TN', 'TUNÍSIA'),
    ('TM', 'TURCOMENISTÃO'),
    ('TR', 'TURQUIA'),
    ('TV', 'TUVALU'),
    ('UA', 'UCRÂNIA'),
    ('UG', 'UGANDA'),
    ('UY', 'URUGUAI'),
    ('UZ', 'UZBEQUISTÃO'),
    ('VU', 'VANUATU'),
    ('VE', 'VENEZUELA'),
    ('VN', 'VIETNÃ'),
    ('ZW', 'ZIMBÁBUE'),
    ('ZM', 'ZÂMBIA'),
    ('ZA', 'ÁFRICA DO SUL'),
    ('AT', 'ÁUSTRIA'),
    ('IN', 'ÍNDIA'),
]
