# Generated by Django 5.0.14 on 2026-07-17 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0014_user_cd_usuario_atualizacao_user_cd_usuario_criacao_and_more",
        ),
        ("tickets", "0002_alter_ticket_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="cd_empresa",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_empresa",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cd_setor",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_setor",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.setor",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="conclusion",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="performers",
            field=models.ManyToManyField(
                blank=True,
                related_name="performed_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberto"),
                    ("received", "Recebido"),
                    ("done", "Concluido"),
                    ("cancelled", "Cancelado"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MotivoServicoSuporte",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_motivo_servico_suporte",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nm_motivo", models.CharField(max_length=120, verbose_name="motivo")),
                ("sn_ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "suporte_motivo_servico",
                "ordering": ("nm_motivo",),
                "unique_together": {("cd_empresa", "nm_motivo")},
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="cd_motivo",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_motivo_servico_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.motivoservicosuporte",
            ),
        ),
        migrations.CreateModel(
            name="OficinaSuporte",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_oficina_suporte",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "nm_oficina",
                    models.CharField(max_length=120, verbose_name="oficina"),
                ),
                (
                    "ds_descricao",
                    models.CharField(
                        blank=True, max_length=220, verbose_name="descricao"
                    ),
                ),
                ("sn_ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "usuarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="oficinas_suporte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "suporte_oficina",
                "ordering": ("nm_oficina",),
                "unique_together": {("cd_empresa", "nm_oficina")},
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="cd_oficina",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_oficina_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.oficinasuporte",
            ),
        ),
        migrations.CreateModel(
            name="PrioridadeSuporte",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "cd_prioridade_suporte",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "nm_prioridade",
                    models.CharField(max_length=80, verbose_name="prioridade"),
                ),
                (
                    "nr_peso",
                    models.PositiveIntegerField(default=3, verbose_name="peso"),
                ),
                (
                    "ds_cor",
                    models.CharField(blank=True, max_length=20, verbose_name="cor"),
                ),
                ("sn_ativo", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        db_column="cd_empresa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "suporte_prioridade",
                "ordering": ("nr_peso", "nm_prioridade"),
                "unique_together": {("cd_empresa", "nm_prioridade")},
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="cd_prioridade",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_prioridade_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.prioridadesuporte",
            ),
        ),
    ]
