# Generated by Django 5.0.14 on 2026-07-17 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0014_user_cd_usuario_atualizacao_user_cd_usuario_criacao_and_more",
        ),
        (
            "tickets",
            "0003_ticket_cd_empresa_ticket_cd_setor_ticket_conclusion_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="motivoservicosuporte",
            options={
                "ordering": ("cd_oficina__nm_oficina", "nm_motivo"),
                "verbose_name": "Motivo de serviço",
                "verbose_name_plural": "Motivos de serviço",
            },
        ),
        migrations.AlterModelOptions(
            name="oficinasuporte",
            options={
                "ordering": ("nm_oficina",),
                "verbose_name": "Oficina de suporte",
                "verbose_name_plural": "Oficinas de suporte",
            },
        ),
        migrations.AlterModelOptions(
            name="prioridadesuporte",
            options={
                "ordering": ("nr_peso", "nm_prioridade"),
                "verbose_name": "Prioridade de suporte",
                "verbose_name_plural": "Prioridades de suporte",
            },
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Chamado",
                "verbose_name_plural": "Chamados",
            },
        ),
        migrations.AlterUniqueTogether(
            name="motivoservicosuporte",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="motivoservicosuporte",
            name="cd_oficina",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_oficina_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.oficinasuporte",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cd_motivo",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_motivo_servico_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.motivoservicosuporte",
                verbose_name="motivo",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cd_oficina",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_oficina_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.oficinasuporte",
                verbose_name="oficina",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cd_prioridade",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_prioridade_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.prioridadesuporte",
                verbose_name="prioridade",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cd_setor",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_setor",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.setor",
                verbose_name="setor",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="description",
            field=models.TextField(blank=True, verbose_name="descrição"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="module",
            field=models.CharField(max_length=80, verbose_name="módulo"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                default="normal", max_length=30, verbose_name="prioridade textual"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="sector",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="setor textual"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=180, verbose_name="título"),
        ),
        migrations.AlterUniqueTogether(
            name="motivoservicosuporte",
            unique_together={("cd_empresa", "cd_oficina", "nm_motivo")},
        ),
    ]
