# Generated by Codex on 2026-07-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0014_user_cd_usuario_atualizacao_user_cd_usuario_criacao_and_more"),
        ("tickets", "0004_alter_motivoservicosuporte_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prioridadesuporte",
            name="nr_peso",
            field=models.PositiveIntegerField(default=0, verbose_name="peso"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cd_motivo_conclusao",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_motivo_conclusao_suporte",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets_concluidos",
                to="tickets.motivoservicosuporte",
                verbose_name="motivo da conclusao",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="performed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TicketTransferenciaSuporte",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("cd_transferencia_suporte", models.BigAutoField(primary_key=True, serialize=False)),
                ("dh_transferencia", models.DateTimeField(default=django.utils.timezone.now)),
                ("ds_observacao", models.CharField(blank=True, max_length=240, verbose_name="observacao")),
                ("cd_empresa", models.ForeignKey(db_column="cd_empresa", on_delete=django.db.models.deletion.PROTECT, to="accounts.empresa")),
                ("cd_oficina_destino", models.ForeignKey(db_column="cd_oficina_destino", on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tickets.oficinasuporte")),
                ("cd_oficina_origem", models.ForeignKey(blank=True, db_column="cd_oficina_origem", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tickets.oficinasuporte")),
                ("cd_ticket", models.ForeignKey(db_column="cd_ticket", on_delete=django.db.models.deletion.CASCADE, related_name="transferencias", to="tickets.ticket")),
                ("cd_usuario", models.ForeignKey(blank=True, db_column="cd_usuario", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Transferencia de chamado",
                "verbose_name_plural": "Transferencias de chamados",
                "db_table": "suporte_ticket_transferencia",
                "ordering": ("-dh_transferencia",),
            },
        ),
        migrations.CreateModel(
            name="UsuarioOficinaSuporte",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                ("cd_usuario_oficina_suporte", models.BigAutoField(primary_key=True, serialize=False)),
                ("sn_ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("sn_atende", models.BooleanField(default=True, verbose_name="atende")),
                ("sn_solicita", models.BooleanField(default=True, verbose_name="solicita")),
                ("cd_empresa", models.ForeignKey(db_column="cd_empresa", on_delete=django.db.models.deletion.PROTECT, to="accounts.empresa")),
                ("cd_oficina", models.ForeignKey(db_column="cd_oficina_suporte", on_delete=django.db.models.deletion.PROTECT, to="tickets.oficinasuporte", verbose_name="oficina")),
                ("cd_usuario", models.ForeignKey(db_column="cd_usuario", on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name="usuario")),
            ],
            options={
                "verbose_name": "Usuario x oficina",
                "verbose_name_plural": "Usuarios x oficinas",
                "db_table": "suporte_usuario_oficina",
                "ordering": ("cd_usuario__username", "cd_oficina__nm_oficina"),
                "unique_together": {("cd_empresa", "cd_usuario", "cd_oficina")},
            },
        ),
    ]
