# Generated by Django 5.0.14 on 2026-07-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_suporte_atendimento_oficina"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Aberto"),
                    ("received", "Recebido"),
                    ("done", "Concluido"),
                    ("not_done", "Não concluído"),
                    ("cancelled", "Cancelado"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
