# Generated by Django 5.0.14 on 2026-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_motivoconclusaosuporte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ds_observacao_conclusao",
            field=models.TextField(blank=True, verbose_name="observação da conclusão"),
        ),
    ]
