# Generated by Django 4.2.30 on 2026-06-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enfermagem", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="boardingautoconfig",
            table="configuracao_automatica_painel",
        ),
        migrations.AlterModelTable(
            name="boardingstatus",
            table="status_painel",
        ),
    ]
