# Generated by Django 4.2.30 on 2026-06-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ti", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="agentevent",
            table="evento_agente",
        ),
        migrations.AlterModelTable(
            name="agentmachine",
            table="maquina_agente",
        ),
    ]
