from django.urls import path

from . import views


app_name = "atendimento"

urlpatterns = [
    path("agendamento/agendar/", views.agendar_consultar_paciente, name="agendar"),
    path("agendamento/agendamentos/", views.agendamentos_operacionais, name="agendamentos-operacionais"),
    path("agendamento/pacientes/<int:cd_paciente>/", views.cadastro_paciente, name="revisar-paciente-agendamento"),
    path("agendamento/pacientes/novo/", views.cadastro_paciente, name="cadastro-paciente-agendamento"),
    path("pacientes/cadastro/", views.cadastro_paciente_geral, name="cadastro-paciente-novo"),
    path("pacientes/cadastro/<int:cd_paciente>/", views.cadastro_paciente_geral, name="cadastro-paciente"),
    path("pacientes/cadastro/<int:cd_paciente>/alternar-status/", views.alternar_status_paciente, name="alternar-status-paciente"),
    path("agendamento/pacientes/<int:cd_paciente>/agenda/", views.selecionar_agenda, name="selecionar-agenda"),
    path("agendamento/<int:cd_agendamento>/comprovante/", views.comprovante_agendamento, name="comprovante-agendamento"),
    path("agendamento/pacientes/<int:cd_paciente>/confirmar/", views.confirmar_agendamento, name="confirmar-agendamento"),
    path("pacientes/verificar-unico/", views.verificar_paciente_unico, name="verificar-paciente-unico"),
    path("agendamento/atender/", views.screen, {"screen": "atender-agendamento"}, name="atender-agendamento"),
    path("recepcao/", views.recepcao, name="recepcao"),
    path("recepcao/<int:cd_agendamento>/", views.recepcionar_agendamento, name="recepcionar-agendamento"),
    path("atendimentos/", views.atendimentos, name="atendimentos"),
    path("pep/", views.pep, name="pep"),
    path("pep/<int:cd_atendimento>/chamar/", views.pep_chamar, name="pep-chamar"),
    path("paineis-chamada/", views.paineis_chamada, name="paineis-chamada"),
    path("painel-chamada/", views.painel_chamada_publico, name="painel-chamada-publico"),
    path("classificacao/", views.fila_classificacao, name="fila-classificacao"),
    path("consultas/", views.fila_medica, name="fila-medica"),
    path("consultas/<int:cd_atendimento>/abrir/", views.abrir_consulta, name="abrir-consulta"),
    path("agendamento/<int:cd_agendamento>/pre-atendimento/", views.iniciar_pre_atendimento, name="pre-atendimento"),
    path("atendimento/<int:cd_atendimento>/pre-atendimento/", views.iniciar_pre_atendimento_atendimento, name="pre-atendimento-atendimento"),
    path("agendamento/<int:cd_agendamento>/iniciar-atendimento/", views.iniciar_atendimento, name="iniciar-atendimento"),
    path("atendimento/ficha/<int:cd_atendimento>/", views.ficha_atendimento, name="ficha-atendimento"),
    path("atendimento/ficha/<int:cd_atendimento>/imprimir/", views.imprimir_atendimento, name="imprimir-atendimento"),
    path("documentos/modelos/", views.modelos_documento, name="modelos-documento"),
    path("documentos/modelos/<int:cd_modelo>/", views.modelos_documento, name="editar-modelo-documento"),
    path("documentos/<int:cd_documento>/imprimir/", views.imprimir_documento_clinico, name="imprimir-documento-clinico"),
    path("documentos/<int:cd_documento>/copiar/", views.copiar_documento_clinico, name="copiar-documento-clinico"),
    path("atendimento/ficha/<int:cd_atendimento>/exames/novo/", views.solicitar_exame, name="solicitar-exame"),
    path("exames/<int:cd_solicitacao>/resultado/", views.resultado_exame, name="resultado-exame"),
    path("atendimento/ficha/<int:cd_atendimento>/prescrever/", views.prescrever, name="prescrever"),
    path("atendimento/ficha/<int:cd_atendimento>/evoluir/", views.evoluir, name="evoluir"),
    path("atendimento/ficha/<int:cd_atendimento>/alta/", views.conceder_alta, name="conceder-alta"),
    path("atendimento/ficha/<int:cd_atendimento>/finalizar/", views.finalizar_atendimento, name="finalizar-atendimento"),
    path("agendamento/consultar/", views.screen, {"screen": "consultar-agendamento"}, name="consultar-agendamento"),
    path("agendamento/agendas/", views.screen, {"screen": "agendas"}, name="agendas"),
    path("agendamento/gerar-agenda/", views.gerar_agenda, name="gerar-agenda"),
    path("agendamento/tabelas/convenios/", views.screen, {"screen": "convenios-agendamento"}, name="convenios-agendamento"),
    path("agendamento/tabelas/tipos-atendimento/", views.screen, {"screen": "tipos-atendimento-agendamento"}, name="tipos-atendimento-agendamento"),
    path("agendamento/tabelas/especialidades/", views.screen, {"screen": "especialidades-agendamento"}, name="especialidades-agendamento"),
    path("atendimento/", views.screen, {"screen": "atendimento"}, name="atendimento"),
    path("atendimento/demanda-espontanea/", views.demanda_espontanea, name="demanda-espontanea"),
    path("atendimento/consultar/", views.screen, {"screen": "consulta-atendimento"}, name="consulta-atendimento"),
    path("atendimento/pacientes/novo/", views.screen, {"screen": "cadastro-paciente-atendimento"}, name="cadastro-paciente-atendimento"),
    path("atendimento/tabelas/convenios/", views.screen, {"screen": "convenios-atendimento"}, name="convenios-atendimento"),
    path("atendimento/tabelas/tipos-atendimento/", views.screen, {"screen": "tipos-atendimento-atendimento"}, name="tipos-atendimento-atendimento"),
    path("atendimento/tabelas/especialidades/", views.screen, {"screen": "especialidades-atendimento"}, name="especialidades-atendimento"),
    path("tabelas/convenios/", views.screen, {"screen": "convenios"}, name="convenios"),
    path("tabelas/tipos-atendimento/", views.screen, {"screen": "tipos-atendimento"}, name="tipos-atendimento"),
    path("tabelas/especialidades/", views.screen, {"screen": "especialidades"}, name="especialidades"),
    path("cadastros/profissionais/", views.profissionais, name="profissionais"),
    path("cadastros/profissionais/novo/", views.cadastro_profissional, name="cadastro-profissional-novo"),
    path("cadastros/profissionais/<int:cd_prestador>/", views.cadastro_profissional, name="cadastro-profissional"),
    path("cadastros/profissionais/<int:cd_prestador>/alternar-status/", views.alternar_status_prestador, name="alternar-status-prestador"),
    path("tabelas/escalas/", views.screen, {"screen": "escalas"}, name="escalas"),
    path("tabelas/salas/", views.screen, {"screen": "salas"}, name="salas"),
    path("relatorios/agendamentos/", views.screen, {"screen": "relatorio-agendamentos"}, name="relatorio-agendamentos"),
    path("relatorios/atendimentos/", views.screen, {"screen": "relatorio-atendimentos"}, name="relatorio-atendimentos"),
    path("relatorios/produtividade/", views.screen, {"screen": "relatorio-produtividade"}, name="relatorio-produtividade"),
]
