# Generated by Django 4.2.30 on 2026-06-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="reportquery",
            table="consulta_relatorio",
        ),
        migrations.AlterModelTable(
            name="reportqueryversion",
            table="versao_consulta_relatorio",
        ),
    ]
