"""Operações históricas de dados da migration 0022."""

# Generated by Django 5.0.14 on 2026-06-28 14:14

import django.db.models.deletion
import django.utils.timezone
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models


def preparar_vigencias_e_pastas(apps, schema_editor):
    AgendaProfissional = apps.get_model("atendimento", "AgendaProfissional")
    PastaDocumento = apps.get_model("atendimento", "PastaDocumento")
    for agenda in AgendaProfissional.objects.all().iterator():
        agenda.dt_fim = agenda.dt_inicio + timedelta(days=90)
        agenda.save(update_fields=["dt_fim"])
    for ordem, (nome, tipo) in enumerate(
        [
            ("Cabeçalhos", "CABECALHOS"),
            ("Rodapés", "RODAPES"),
            ("Documentos de admissão", "ADMISSAO"),
            ("Documentos de alta", "ALTA"),
        ]
    ):
        PastaDocumento.objects.get_or_create(
            cd_empresa=None,
            cd_pasta_pai=None,
            nm_pasta=nome,
            defaults={
                "tp_pasta": tipo,
                "nr_ordem": ordem,
                "sn_sistema": True,
                "sn_editavel": False,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_setor_setorusuario"),
        ("atendimento", "0021_modelodocumento_documentoclinico"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="modelodocumento",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="dt_fim",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="agendaprofissional",
            name="dt_inicio",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="cd_cabecalho",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_cabecalho",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_cabecalho",
                to="atendimento.modelodocumento",
            ),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="cd_rodape",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_rodape",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_rodape",
                to="atendimento.modelodocumento",
            ),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="cd_versao_anterior",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_versao_anterior",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versoes_seguintes",
                to="atendimento.modelodocumento",
            ),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="ds_alteracoes_versao",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="ds_css_impressao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="ds_css_tela",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="ds_html_impressao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="ds_html_tela",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="ds_projeto_impressao",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="ds_projeto_tela",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="nr_versao",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="sn_editavel",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="sn_sistema",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="sn_versao_atual",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="tp_elemento",
            field=models.CharField(
                choices=[
                    ("DOCUMENTO", "Documento"),
                    ("CABECALHO", "Cabeçalho"),
                    ("RODAPE", "Rodapé"),
                ],
                default="DOCUMENTO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="modelodocumento",
            name="cd_empresa",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_empresa",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.empresa",
            ),
        ),
        migrations.CreateModel(
            name="PastaDocumento",
            fields=[
                (
                    "dh_criacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("dh_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "cd_pasta_documento",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("nm_pasta", models.CharField(max_length=120)),
                (
                    "tp_pasta",
                    models.CharField(
                        choices=[
                            ("GERAL", "Geral"),
                            ("CABECALHOS", "Cabeçalhos"),
                            ("RODAPES", "Rodapés"),
                            ("ADMISSAO", "Documentos de admissão"),
                            ("ALTA", "Documentos de alta"),
                        ],
                        default="GERAL",
                        max_length=20,
                    ),
                ),
                ("nr_ordem", models.PositiveIntegerField(default=0)),
                ("sn_sistema", models.BooleanField(default=False)),
                ("sn_editavel", models.BooleanField(default=True)),
                ("sn_ativo", models.BooleanField(default=True)),
                (
                    "cd_empresa",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_empresa",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.empresa",
                    ),
                ),
                (
                    "cd_pasta_pai",
                    models.ForeignKey(
                        blank=True,
                        db_column="cd_pasta_pai",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subpastas",
                        to="atendimento.pastadocumento",
                    ),
                ),
                (
                    "cd_usuario_atualizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_atualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cd_usuario_criacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "pasta_documento",
                "ordering": ("nr_ordem", "nm_pasta"),
            },
        ),
        migrations.AddField(
            model_name="modelodocumento",
            name="cd_pasta",
            field=models.ForeignKey(
                blank=True,
                db_column="cd_pasta",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="atendimento.pastadocumento",
            ),
        ),
        migrations.RunPython(preparar_vigencias_e_pastas, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="modelodocumento",
            constraint=models.UniqueConstraint(
                fields=("cd_empresa", "tp_documento", "nm_modelo", "nr_versao"),
                name="modelo_documento_versao_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="pastadocumento",
            constraint=models.UniqueConstraint(
                fields=("cd_empresa", "cd_pasta_pai", "nm_pasta"),
                name="pasta_documento_unica",
            ),
        ),
    ]
