# Generated by Django 4.2.30 on 2026-06-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="socialattendance",
            table="atendimento_social",
        ),
        migrations.AlterModelTable(
            name="socialperiod",
            table="periodo_social",
        ),
    ]
